(async()=>{'use strict';
const $=id=>document.getElementById(id),API=RecykeKit,reg=await fetch('assets/registry.json').then(r=>r.json()),assets=new Map(reg.assets.map(a=>[a.assetId,a])),images=new Map(),metas=new Map(),scenes={};
const load=async uri=>{if(images.has(uri))return images.get(uri);let img=new Image();img.src=uri;await img.decode();images.set(uri,img);return img;};
await Promise.all([...reg.assets.flatMap(a=>a.render.variants.map(v=>load(v.uri))),...reg.characters.map(async r=>{await load(r.uri);metas.set(r.metadata,await fetch(r.metadata).then(r=>r.json()));}),...['mini','big'].map(async f=>scenes[f]=await fetch(`scenes/${f}.json`).then(r=>r.json()))]);
let family=new URLSearchParams(location.search).get('size')==='big'?'big':'mini',scene,game,snapshot,hero='jane',hidden=new Set(),selection,detailCanvas,dtLast=0,animationTime=0,currentTab='demo';const keys=new Set(),canvas=$('scene'),ctx=canvas.getContext('2d');
const isForm=t=>t instanceof Element&&!!t.closest('input,select,textarea,button,a,summary,[contenteditable]');
function fit(){if(!$('stage').clientWidth)return;CADPixelGrid.applyScene(canvas,{availableWidth:$('stage').clientWidth-8,availableHeight:660,maxScale:3});let dpr=window.devicePixelRatio||1,scale=Math.round(canvas.getBoundingClientRect().width*dpr/canvas.width);$('grid-status').textContent=`${canvas.width} × ${canvas.height} native · ${scale} device px / art px`;}
function familyChange(f){family=f;scene=scenes[f];game=API.create(scene,assets);snapshot=game.snapshot();keys.clear();canvas.width=scene.viewport[0];canvas.height=scene.viewport[1];hidden.clear();document.body.classList.toggle('big',f==='big');document.querySelectorAll('[data-family]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.family===f)));
 $('family-note').textContent=f==='mini'?'Independent native mini kit · approved Proposal A + held crouch':'Independent native big kit · unchanged archived hero appearances for scale review';$('crouch-help').hidden=f==='big';$('asset-count').textContent=reg.assets.filter(a=>a.family===f).length;
 $('sections').replaceChildren(...scene.sections.map(sec=>{let b=document.createElement('button');b.textContent=sec.name;b.onclick=()=>{game.reset({x:sec.x,y:scene.spawn.y});snapshot=game.snapshot();keys.clear();canvas.focus();};return b;}));
 $('layers').replaceChildren(...reg.layers.filter(l=>l.id!=='sky').map(l=>{let label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=true;check.onchange=()=>{check.checked?hidden.delete(l.id):hidden.add(l.id);};label.append(check,document.createTextNode(l.id));return label;}));
 let url=new URL(location.href);url.searchParams.set('size',f);history.replaceState(null,'',url);renderCatalog();fit();}
function selected(a){selection=a;$('asset-name').textContent=a.name;$('metadata').textContent=JSON.stringify(a,null,2);$('variant').replaceChildren(...a.render.variants.map((v,i)=>new Option(`${i+1} / ${a.render.variants.length}`,i)));$('state').replaceChildren(...Object.keys(a.animation.states).map(s=>new Option(s,s)));$('frame').max=a.render.frameCount-1;$('frame').value=0;detailCanvas=document.createElement('canvas');detailCanvas.width=a.native.width+16;detailCanvas.height=a.native.height+16;$('detail-art').replaceChildren(detailCanvas);animationTime=0;
 const rows=[['Native dimensions',`${a.native.width} × ${a.native.height} px`],['Stable ID',a.assetId],['Anchor',`${a.native.origin.join(', ')} · ${a.native.originName}`],['Draw layer',a.render.layer],['Collision',a.collision.decorative?'Decorative · no collision':a.collision.defaults.map(c=>`${c.kind}: ${c.width} × ${c.height} at ${c.x}, ${c.y}`).join('; ')],['Behavior',a.collision.behavior],['Connections',a.sockets.map(s=>`${s.id}: (${s.x}, ${s.y}) ${s.type}`).join('; ')||'No automatic connection'],['Animation',`${a.render.frameCount} authored frames; ${Object.keys(a.animation.states).join(', ')}`],['Source',a.source.type+' · '+a.source.file],['Tags',a.tags.join(', ')]];
 $('asset-info').replaceChildren(...rows.flatMap(([k,v])=>{let dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=k;dd.textContent=v;return [dt,dd];}));let meta=document.createElement('a'),png=document.createElement('a');meta.textContent='Asset metadata';meta.href=`assets/${family}/${a.assetId.split('.').at(-1)}.json`;meta.download='';png.textContent='Native PNG sheet';png.href=a.render.variants[0].uri;png.download='';$('asset-links').replaceChildren(meta,png);document.querySelectorAll('.asset-card').forEach(b=>b.classList.toggle('selected',b.dataset.id===a.assetId));}
function renderCatalog(){let q=$('search').value.toLowerCase(),kind=$('kind').value,list=reg.assets.filter(a=>a.family===family&&(!kind||a.kind===kind)&&(!q||[a.name,a.assetId,...a.tags].join(' ').toLowerCase().includes(q))).sort((a,b)=>['building','interactive','animated','prop','platform','background','terrain'].indexOf(a.kind)-['building','interactive','animated','prop','platform','background','terrain'].indexOf(b.kind));$('results').textContent=`${list.length} definitions`;const frag=document.createDocumentFragment();for(const a of list){let b=document.createElement('button');b.className='asset-card';b.dataset.id=a.assetId;b.setAttribute('aria-label',`${a.name}, ${a.native.width} by ${a.native.height} native pixels`);let art=document.createElement('div');art.className='art';let c=document.createElement('canvas');c.width=a.native.width;c.height=a.native.height;API.drawAsset(c.getContext('2d'),a,images.get(a.render.variants[0].uri),a.native.origin[0],a.native.origin[1]);art.append(c);let title=document.createElement('strong');title.textContent=a.name;let sub=document.createElement('small');sub.textContent=`${a.native.width}×${a.native.height} · ${a.collision.decorative?'DECORATIVE':a.collision.defaults[0].kind.toUpperCase()} · ${a.render.variants.length} variation${a.render.variants.length===1?'':'s'}`;b.append(art,title,sub);b.onclick=()=>selected(a);frag.append(b);}$('asset-grid').replaceChildren(frag);if(list.length)selected(list.find(a=>a.assetId===selection?.assetId)||list[0]);else{$('asset-info').replaceChildren();$('asset-name').textContent='No matching assets';}}
function showTab(id){currentTab=['demo','catalog','notes'].includes(id)?id:'demo';document.querySelectorAll('.tab').forEach(e=>e.hidden=e.id!==currentTab);document.querySelectorAll('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===currentTab));keys.clear();if(currentTab==='demo')fit();}
function sceneDraw(){snapshot=game.snapshot();API.drawScene(ctx,scene,reg,images,metas,snapshot,{hero,geometry:$('geometry').checked,hidden});let near=Math.abs(snapshot.player.x-scene.door.entryX)<=scene.door.interactionRadius;let text=snapshot.paused?'Paused. P resumes.':snapshot.won?'Entrance open · environment study complete. Restart or inspect the catalog.':near?`${snapshot.doorState.toUpperCase()} · E inspects locks / opens entrance. Review interaction only.`:'Walk toward the concealed entrance. Jump across elevation changes or inspect the raised catwalk.';$('scene-status').textContent=text;$('pause').innerHTML=(snapshot.paused?'Resume':'Pause')+' <kbd>P</kbd>';$('door-state').value=snapshot.doorState;$('interact').disabled=!near||snapshot.doorState==='open'||snapshot.doorState==='opening';}
function drawDetail(){if(!selection||!detailCanvas)return;const a=selection,c=detailCanvas.getContext('2d'),v=Number($('variant').value)||0,state=$('state').value,frame=$('animate').checked?API.frameAt(a,state,animationTime):Number($('frame').value);c.clearRect(0,0,detailCanvas.width,detailCanvas.height);API.drawAsset(c,a,images.get(a.render.variants[v].uri),8+a.native.origin[0],8+a.native.origin[1],{frame});if($('asset-overlay').checked){let ox=8+a.native.origin[0],oy=8+a.native.origin[1];c.strokeStyle='#d4ccad';c.beginPath();c.moveTo(ox-4+.5,oy+.5);c.lineTo(ox+4+.5,oy+.5);c.moveTo(ox+.5,oy-4+.5);c.lineTo(ox+.5,oy+4+.5);c.stroke();for(const b of a.collision.defaults){c.strokeStyle=b.kind==='sensor'?'#dbb578':b.kind==='oneWay'?'#8fcac0':'#b7df53';c.strokeRect(ox+b.x+.5,oy+b.y+.5,b.width-1,b.height-1);}}$('frame-value').textContent=`${frame+1}/${a.render.frameCount}`;if($('animate').checked)$('frame').value=frame;$('asset-links').querySelector('a:last-child').href=a.render.variants[v].uri;}
function tick(now){let dt=dtLast?Math.min(.05,(now-dtLast)/1000):0;dtLast=now;animationTime+=dt;if(currentTab==='demo'){game.update(dt,{left:keys.has('KeyA')||keys.has('ArrowLeft'),right:keys.has('KeyD')||keys.has('ArrowRight'),jump:keys.has('KeyW')||keys.has('ArrowUp'),down:keys.has('KeyS')||keys.has('ArrowDown')});sceneDraw();}else if(currentTab==='catalog')drawDetail();requestAnimationFrame(tick);}
window.addEventListener('keydown',e=>{if(currentTab!=='demo'||isForm(e.target)||e.ctrlKey||e.metaKey||e.altKey||e.isComposing)return;if(['KeyA','KeyD','KeyW','KeyS','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)){e.preventDefault();keys.add(e.code);}else if(!e.repeat&&['KeyP','Escape','KeyR','KeyE'].includes(e.code)){e.preventDefault();if(e.code==='KeyP'||e.code==='Escape'){game.pause(!game.snapshot().paused);keys.clear();}else if(e.code==='KeyR')game.reset();else game.interact();}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();game?.pause(true);dtLast=0;});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();game?.pause(true);dtLast=0;}});document.addEventListener('focusin',e=>{if(isForm(e.target))keys.clear();});
$('reset').onclick=()=>{game.reset();keys.clear();canvas.focus();};$('pause').onclick=()=>{game.pause(!game.snapshot().paused);keys.clear();canvas.focus();};$('hero').onchange=()=>{hero=$('hero').value;canvas.focus();};$('interact').onclick=()=>{game.interact();canvas.focus();};$('door-state').onchange=()=>game.setDoor($('door-state').value);$('search').oninput=renderCatalog;$('kind').onchange=renderCatalog;$('state').onchange=()=>{animationTime=0;};$('frame').oninput=()=>{$('animate').checked=false;};document.querySelectorAll('[data-family]').forEach(b=>b.onclick=()=>familyChange(b.dataset.family));window.addEventListener('hashchange',()=>showTab(location.hash.slice(1)));new ResizeObserver(()=>{if(currentTab==='demo')fit();}).observe($('stage'));window.addEventListener('resize',fit);
familyChange(family);showTab(location.hash.slice(1));window.KitPreview={ready:true,registry:reg,get family(){return family;},get game(){return game;},get scene(){return scene;},selectFamily:familyChange};requestAnimationFrame(tick);
})().catch(e=>{document.getElementById('scene-status').textContent='Could not load the preview. Serve this folder over localhost. '+e.message;console.error(e);});
