const fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const {createCanvas,loadImage}=require('@napi-rs/canvas');
const P=require('./painters.cjs');
const ROOT=path.resolve(__dirname,'..'),WORK=path.resolve(ROOT,'..');
const write=(p,d)=>{fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,typeof d==='string'||Buffer.isBuffer(d)?d:JSON.stringify(d,null,2)+'\n');};
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const registry={schemaVersion:1,packId:'cad.recyke.street-alley',revision:1,status:'review-candidate',sourcePixelWorldUnits:1,palette:P.palette,families:{},layers:[{id:'sky',order:0},{id:'distant',order:10},{id:'architecture',order:20},{id:'scenery',order:30},{id:'playable',order:40},{id:'actors',order:50},{id:'foreground',order:60}],assets:[],characters:[],materialRules:{},assemblies:[]};
function legacy(family){let file=family==='mini'?'recyke-development/recyke-art.js':'archive/pre-mini-2026-09-14/recyke-development/recyke-art.js';let code=fs.readFileSync(path.join(WORK,file),'utf8').replace('window.CADRecykeArt={draw,palette,word};','window.CADRecykeArt={draw,palette,word,machinery,surfaces,pipe,neonSign};');let box={window:{}};vm.runInNewContext(code,box);return {api:box.window.CADRecykeArt,path:file,hash:sha(fs.readFileSync(path.join(WORK,file)))};}
function add(F,key,label,kind,w,h,draw,opt={}){
 const family=F.family,states=opt.states||{idle:{frames:[0],timingMs:[1000],loop:true}},frames=opt.frames||1,variants=opt.variants||1,id=`cad.${family}.recyke.${key}`;
 const anchor=opt.anchor||[0,h],allBounds=[];let sheets=[];
 for(let v=0;v<variants;v++){
  let sheet=createCanvas(w*frames,h),sc=sheet.getContext('2d');
  for(let f=0;f<frames;f++){
   const margin=128,probe=createCanvas(w+2*margin,h+2*margin),pc=probe.getContext('2d');pc.translate(margin,margin);draw(pc,f,v);let im=pc.getImageData(0,0,probe.width,probe.height),minX=w,minY=h,maxX=-1,maxY=-1;
   for(let yy=0;yy<probe.height;yy++)for(let xx=0;xx<probe.width;xx++){let i=(yy*probe.width+xx)*4;if(im.data[i+3]){if(xx<margin||xx>=margin+w||yy<margin||yy>=margin+h)throw Error(`${id} clips v${v} f${f} at ${xx-margin},${yy-margin}`);minX=Math.min(minX,xx-margin);maxX=Math.max(maxX,xx-margin);minY=Math.min(minY,yy-margin);maxY=Math.max(maxY,yy-margin);if(im.data[i+3]!==255)throw Error(`${id}: partial alpha`);}}
   allBounds.push({variant:v,frame:f,x:minX,y:minY,width:maxX-minX+1,height:maxY-minY+1});sc.drawImage(probe,margin,margin,w,h,f*w,0,w,h);
  }
  let uri=`assets/${family}/${key}${variants>1?'-v'+v:''}.png`;let buf=sheet.toBuffer('image/png');write(path.join(ROOT,uri),buf);sheets.push({id:`v${v}`,uri,sha256:sha(buf),width:w*frames,height:h});
 }
 const colliders=(opt.collision||[]).map(c=>({channel:c.kind==='sensor'?'interaction':'world',mask:c.kind==='sensor'?['player']:['player','projectile'],...c}));
 const asset={assetId:id,revision:1,name:label,kind,biome:'recyke',family,approval:'review-candidate',source:opt.source||{type:'new-native',file:`src/${family}.cjs`,renderer:'src/painters.cjs'},native:{width:w,height:h,origin:anchor,originName:opt.originName||'base-left',selectionBounds:{x:0,y:0,width:w,height:h},visibleBounds:allBounds,animationEnvelope:{x:0,y:0,width:w,height:h}},sockets:opt.sockets||[],render:{kind:'sprite-sheet',layer:opt.layer||'scenery',parallax:{x:1,y:1},variants:sheets,frameSize:[w,h],frameCount:frames,allowedFacing:[1],scale:1},collision:{defaults:colliders,decorative:colliders.length===0,behavior:opt.behavior||'none'},properties:{variant:{type:'integer',default:0,min:0,max:variants-1,description:'Explicit visual variation; collision is unchanged.'},state:{type:'enum',values:Object.keys(states),default:Object.keys(states)[0]},...(opt.properties||{})},animation:{states,frameEvents:opt.events||[],timingUnit:'ms',sourceFramesOnly:true,deterministic:true},tags:[family,'recyke',kind,...(opt.tags||[]),'native'],thumbnail:{uri:sheets[0].uri,frame:0,variant:0,nativeSize:[w,h],noResample:true},placement:{snap:1,suggestedGrid:family==='mini'?8:16,preview:'native-art+anchor+collision',repeat:opt.repeat||null,allowScale:false,allowRotation:false}};
 registry.assets.push(asset);write(path.join(ROOT,`assets/${family}/${key}.json`),asset);return asset;
}
(async()=>{
 for(const F of [require('./mini.cjs'),require('./big.cjs')]){
  const S=F.family,L=legacy(S);registry.families[S]={cell:F.cell,actorHeight:F.actorHeight,actorAnchor:F.actorAnchor,viewport:F.viewport,physics:F.physics,authoring:'Independent native recipes; no resizing',characterAppearance:S==='mini'?'Current Proposal A + approved crouch':'Archived approved large masters; historical appearance, unchanged'};
  let source={type:'native-extraction',file:L.path,sha256:L.hash};
  const T=F.terrain;let rule={cellSize:[T.w,T.h],neighbors:{up:1,right:2,down:4,left:8},lookup:{},variation:'explicit v0/v1/v2; seeded in scene generation'};
  for(let m=0;m<16;m++){let k='street-'+m.toString(16);add(F,k,`Street · ${['isolated block','shaft foot','slab left cap','bottom-left corner','shaft top','shaft sides','top-left corner','left edge','slab right cap','bottom-right corner','slab middle','underside','top-right corner','right edge','top','fill'][m]}`,'terrain',T.w,T.h,(c,f,v)=>P.terrain(c,T,m,v),{variants:3,anchor:[0,0],originName:'top-left',layer:'playable',collision:[{kind:'solid',x:0,y:0,width:T.w,height:T.h}],tags:['ground','street','edge','repeat'],sockets:[{id:'left',type:`street-${S}`,x:0,y:0,facing:'left'},{id:'right',type:`street-${S}`,x:T.w,y:0,facing:'right'},{id:'bottom',type:`street-${S}`,x:0,y:T.h,facing:'down'}],repeat:{x:T.w,y:T.h}});rule.lookup[m]=`cad.${S}.recyke.${k}`;}registry.materialRules[S]=rule;
  add(F,'facade','Tenement · window bay','building',F.facade.w,F.facade.h,(c,f,v)=>P.facade(c,F.facade,v),{variants:3,layer:'architecture',tags:['facade','building','windows','wall'],sockets:[{id:'left',type:`facade-${S}`,x:0,y:0,facing:'left'},{id:'right',type:`facade-${S}`,x:F.facade.w,y:0,facing:'right'},{id:'roof',type:`roof-${S}`,x:0,y:-F.facade.h,facing:'up'}],repeat:{x:F.facade.w}});
  add(F,'alley-wall','Alley wall · quiet masonry','building',F.facade.w,F.facade.h,(c,f,v)=>{let {r}=P.pen(c),w=F.facade.w,h=F.facade.h,pitch=S==='mini'?24:56,rows=S==='mini'?16:29;r('wallDark',0,0,w,h);r('seam',0,0,w,2);for(let y=8;y<h;y+=rows){r('wall',0,y,w,1);for(let x=(Math.floor(y/rows)%2)*Math.floor(pitch/2);x<w;x+=pitch)r('wall',x,y,1,Math.min(rows,h-y));}r('plum',v?Math.floor(w*.55):7,Math.floor(h*.62),S==='mini'?15:32,2);r('wallFace',0,2,w,1);},{variants:2,layer:'architecture',tags:['alley','masonry','wall','quiet backdrop'],repeat:{x:F.facade.w}});
  add(F,'shutter','Workshop · closed shutter bay','building',F.shutter.w,F.shutter.h,(c,f,v)=>P.shutter(c,F.shutter,v),{variants:2,layer:'architecture',tags:['facade','workshop','shutter','decorative'],repeat:{x:F.shutter.w}});
  add(F,'roof','Roof cornice · clear / vent / patched','building',F.roof.w,F.roof.h,(c,f,v)=>P.roof(c,F.roof,v),{variants:3,layer:'architecture',tags:['roof','cornice','repeat'],sockets:[{id:'left',type:`roof-${S}`,x:0,y:0,facing:'left'},{id:'right',type:`roof-${S}`,x:F.roof.w,y:0,facing:'right'}],repeat:{x:F.roof.w}});
  add(F,'corner','Masonry return · exposed corner','building',F.corner.w,F.corner.h,(c,f,v)=>P.corner(c,F.corner,v),{variants:2,layer:'architecture',tags:['corner','return','endcap']});
  add(F,'recess','Concealed entrance · deep reveal','building',F.recess.w,F.recess.h,c=>P.recess(c,F.recess),{layer:'architecture',tags:['door','entrance','recess','moral code'],sockets:[{id:'door',type:`door-${S}`,x:Math.floor((F.recess.w-F.door.w)/2),y:0,facing:'front'}]});
  let D=F.door;
  add(F,'concealed-door','Concealed service entrance','interactive',D.w,D.h,(c,f)=>P.door(c,D,f),{frames:7,anchor:[0,D.h],layer:'scenery',tags:['door','entrance','locks','moral code'],states:{sealed:{frames:[0],timingMs:[1000],loop:true},latched:{frames:[1],timingMs:[1000],loop:true},unlatched:{frames:[2],timingMs:[1000],loop:true},opening:{frames:[2,3,4,5,6],timingMs:[180,120,120,120,180],loop:false,endState:'open'},open:{frames:[6],timingMs:[1000],loop:true}},collision:[{kind:'sensor',x:D.x-8,y:D.y-D.h,width:D.opening[0]+16,height:D.opening[1]}],behavior:'none; host may bind sensor to an interaction; artwork does not block horizontal travel',events:[{state:'opening',frameIndex:4,event:'opening-clear'}],properties:{initialVisualState:{type:'enum',values:['sealed','latched','unlatched','open'],default:'sealed',description:'Visual state only; host owns access rules.'}},sockets:[{id:'entry',type:`entry-${S}`,x:D.x+Math.floor(D.opening[0]/2),y:0,facing:'front'}]});
  for(let key of ['pipeH','pipeV']){let d=F[key];add(F,key==='pipeH'?'pipe-horizontal':'pipe-vertical',key==='pipeH'?'Pipe · horizontal coupling':'Pipe · vertical coupling','prop',d.w,d.h,(c,f,v)=>P.pipe(c,d,v),{variants:2,anchor:[0,0],originName:'top-left',tags:['pipe','connector','rust'],repeat:key==='pipeH'?{x:d.w}:{y:d.h},sockets:key==='pipeH'?[{id:'in',type:`pipe-${S}`,x:0,y:Math.floor(d.h/2),facing:'left'},{id:'out',type:`pipe-${S}`,x:d.w,y:Math.floor(d.h/2),facing:'right'}]:[{id:'in',type:`pipe-${S}`,x:Math.floor(d.w/2),y:0,facing:'up'},{id:'out',type:`pipe-${S}`,x:Math.floor(d.w/2),y:d.h,facing:'down'}]});}
  add(F,'pipe-elbow','Pipe · down elbow','prop',F.elbow.w,F.elbow.h,(c,f,v)=>P.elbow(c,F.elbow,v),{variants:2,anchor:[0,0],originName:'top-left',tags:['pipe','connector','corner'],sockets:[{id:'in',type:`pipe-${S}`,x:0,y:F.elbow.y+Math.floor(F.elbow.bore/2),facing:'left'},{id:'out',type:`pipe-${S}`,x:F.elbow.x+Math.floor(F.elbow.bore/2),y:F.elbow.h,facing:'down'}]});
  add(F,'vent-fan','Wall extractor · turning fan','animated',F.vent.w,F.vent.h,(c,f)=>P.vent(c,F.vent,f),{frames:4,states:{idle:{frames:[0,1,2,3],timingMs:[140,140,140,140],loop:true}},tags:['vent','fan','machinery'],layer:'scenery'});
  add(F,'lamp','Street lamp · warm flicker','animated',F.lamp.w,F.lamp.h,(c,f)=>P.lamp(c,F.lamp,f),{frames:4,states:{idle:{frames:[0,1,2,3,2],timingMs:[900,800,900,70,600],loop:true}},tags:['lamp','light','street'],anchor:[F.lamp.stem,0],originName:'mount'});
  add(F,'scrap','Sorted scrap · three clusters','prop',F.scrap.w,F.scrap.h,(c,f,v)=>P.scrap(c,F.scrap,v),{variants:3,tags:['scrap','debris','metal','decorative']});
  add(F,'skyline','Distant Recyke · tower strip','background',F.skyline.w,F.skyline.h,(c,f,v)=>P.skyline(c,F.skyline,v),{variants:2,layer:'distant',tags:['skyline','towers','background'],repeat:{x:F.skyline.w}});
  add(F,'cable','Sagging utility cable','prop',F.cable.w,F.cable.h,c=>P.cable(c,F.cable),{anchor:[0,0],originName:'top-left',tags:['wire','cable','repeat'],sockets:[{id:'left',type:`cable-${S}`,x:0,y:F.cable.base,facing:'left'},{id:'right',type:`cable-${S}`,x:F.cable.w,y:F.cable.base,facing:'right'}]});
  add(F,'puddle','Puddle · reflected light','animated',F.puddle.w,F.puddle.h,(c,f)=>P.puddle(c,F.puddle,f),{frames:3,states:{idle:{frames:[0,1,2],timingMs:[500,500,500],loop:true}},layer:'foreground',tags:['puddle','reflection','wet','decorative']});
  for(const [key,label] of [['crate','Cargo crate · low'],['crateTall','Cargo crate · tall']]){let [w,h]=F[key];add(F,key==='crate'?'crate-low':'crate-tall',label,'platform',w,h,c=>L.api.surfaces(c,{size:S,view:{width:w,height:F.viewport[1]},camera:0,time:0,platforms:[{x:0,y:0,w,h,kind:'crate'}]}),{anchor:[Math.floor(w/2),h],originName:'base-center',layer:'playable',collision:[{kind:'solid',x:-Math.floor(w/2),y:-h,width:w,height:h}],source:{...source,function:'surfaces',extraction:'exact native rectangle; no resizing'},tags:['crate','cover','elevation']});}
  for(let type of ['left','middle','right','single']){let d=F.platform;add(F,'catwalk-'+type,'Catwalk · '+type,'platform',d.w,d.h,c=>{const {r}=P.pen(c);r('ink',0,0,d.w,d.h);r('edge',0,0,d.w,2);r('steelDark',0,2,d.w,d.h-2);for(let x=3;x<d.w-3;x+=d.bolt)r('steel',x,3,Math.min(5,d.w-x),2);if(type==='left'||type==='single')r('steelLight',0,2,2,d.h-2);if(type==='right'||type==='single')r('ink',d.w-2,2,2,d.h-2);},{anchor:[0,0],originName:'top-left',layer:'playable',collision:[{kind:'oneWay',x:0,y:0,width:d.w,height:d.h}],tags:['platform','catwalk','edge','repeat'],repeat:{x:d.w},sockets:[{id:'left',type:`catwalk-${S}`,x:0,y:0,facing:'left'},{id:'right',type:`catwalk-${S}`,x:d.w,y:0,facing:'right'}]});}
  add(F,'support','Catwalk support · decorative','prop',F.support.w,F.support.h,c=>{let {r}=P.pen(c);r('wallDark',0,0,F.support.w,F.support.h);r('steel',1,0,1,F.support.h);r('steelDark',2,0,F.support.w-2,F.support.h);},{tags:['support','post','decorative'],anchor:[0,0],originName:'top-left',repeat:{y:F.support.h}});
  add(F,'drain','Street drain','prop',F.drain.w,F.drain.h,c=>{let {r}=P.pen(c);r('pit',0,0,F.drain.w,F.drain.h);r('steelDark',0,0,F.drain.w,1);for(let x=2;x<F.drain.w-1;x+=F.drain.step)r('steel',x,2,1,F.drain.h-3);},{layer:'foreground',tags:['drain','grate','street']});
  add(F,'fix-sign','Repair shop · FIX sign','animated',F.sign.w,F.sign.h,(c,f)=>{let {r}=P.pen(c),d=F.sign;r('seam',0,0,d.w,d.h);r('plum',2,2,d.w-4,d.h-4);r(f===1?'wallFace':'teal',2,2,1,d.h-4);let gap=S==='mini'?10:16,top=S==='mini'?6:12;[...'FIX'].forEach((ch,i)=>L.api.word(c,ch,Math.floor(d.w/2)-2,top+i*gap,f===1&&i===1?'wallFace':'teal'));r('steelDark',d.w-4,d.h-4,2,2);},{frames:2,states:{idle:{frames:[0,1,0],timingMs:[1800,90,800],loop:true}},tags:['sign','neon','shop','FIX'],source:{type:'adapted-native',file:L.path,function:'neonSign / word',note:'FIX is existing prototype signage, not new story text.'}});
  add(F,'poster','Layered paper notices','prop',F.poster.w,F.poster.h,(c,f,v)=>{let {r}=P.pen(c),d=F.poster;r('rustDark',0,0,d.w,d.h);r('muted',2,2,d.w-5,d.h-5);r(v?'plum':'wallFace',4,4,d.w-9,Math.floor(d.h/4));for(let y=Math.floor(d.h/2);y<d.h-5;y+=4)r('steelDark',4,y,d.w-10-(y%3),1);r('wallDark',0,d.h-4,6,4);},{variants:2,tags:['poster','paper','notice','no canon text']});
  for(const key of ['bins','press','boiler']){let def=F.reuse[key],frames=key==='bins'?1:key==='press'?12:20,period=key==='press'?2*Math.PI/.9:5;add(F,key,key==='bins'?'Refuse bin + bag':key==='press'?'Sorting press · working cycle':'Boiler + native steam',key==='bins'?'prop':'animated',def.rect[2],def.rect[3],(c,f)=>{const full=createCanvas(S==='mini'?2112:3900,F.viewport[1]);L.api.machinery(full.getContext('2d'),{size:S,view:{width:full.width,height:full.height},config:{worldWidth:full.width},camera:0,time:f*period/frames},S==='mini');c.drawImage(full,def.rect[0],def.rect[1],def.rect[2],def.rect[3],0,0,def.rect[2],def.rect[3]);},{frames,states:{idle:{frames:Array.from({length:frames},(_,i)=>i),timingMs:Array(frames).fill(Math.round(period*1000/frames)),loop:true}},anchor:def.anchor,tags:[key,'machinery','reused','decorative'],source:{...source,function:'machinery',nativeCrop:def.rect,noResampling:true}});}
  add(F,'train-car','Public rail · carriage','background',F.train.w,F.train.h,c=>{let {r}=P.pen(c),d=F.train;r('seam',0,0,d.w,d.bodyH);r('wallFace',2,2,d.w-4,d.bodyH-4);r('rust',2,2,d.w-4,3);r('violet',2,5,d.w-4,1);for(let xx=6;xx<=d.w-d.winW-3;xx+=d.winStep){r('seam',xx,9,d.winW,d.winH);r('window',xx+1,10,d.winW-2,d.winH-2);r('windowLight',xx+2,10,S==='mini'?3:5,2);}r('teal',3,d.bodyH-5,d.w-6,1);r('steelDark',5,d.bodyH-1,8,3);r('steelDark',d.w-14,d.bodyH-1,8,3);},{layer:'distant',tags:['train','rail','public','background'],source:{type:'adapted-native',file:L.path,function:'skyline train',note:'Separated native carriage; movement belongs to scene provider.'},sockets:[{id:'next',type:`rail-car-${S}`,x:F.train.w+4,y:0,facing:'right'}]});
  add(F,'rail-beam','Elevated rail · repeat beam','background',S==='mini'?48:96,S==='mini'?8:12,c=>{let {r}=P.pen(c),w=S==='mini'?48:96,h=S==='mini'?8:12;r('seam',0,0,w,h);r('steel',0,0,w,1);r('wallFace',0,3,w,1);for(let x=4;x<w;x+=12)r('steelDark',x,5,5,1);},{layer:'distant',anchor:[0,0],originName:'top-left',tags:['rail','beam','repeat'],repeat:{x:S==='mini'?48:96}});
  // Copy unchanged approved reference sheets, not editable actor assets in this kit.
  for(const hero of ['jane','jessie']){let base=S==='mini'?'recyke-development':'archive/pre-mini-2026-09-14/recyke-development';let src=`${base}/assets/${hero}/${hero}-${S}.png`,meta=`${base}/assets/${hero}/${hero}-animation.json`;let bytes=fs.readFileSync(path.join(WORK,src)),json=JSON.parse(fs.readFileSync(path.join(WORK,meta),'utf8')),uri=`reference/${hero}-${S}.png`,mu=`reference/${hero}-${S}.json`;write(path.join(ROOT,uri),bytes);write(path.join(ROOT,mu),json);registry.characters.push({id:hero,family:S,uri,metadata:mu,source:src,sha256:sha(bytes),cell:F.cell,anchor:F.actorAnchor,standingHeight:F.actorHeight,appearance:S==='mini'?'Approved Proposal A':'Archived approved large appearance, unchanged'});}
 }
 write(path.join(ROOT,'assets/registry.json'),registry);console.log(`Built ${registry.assets.length} native definitions, ${registry.characters.length} unchanged hero references.`);
})().catch(e=>{console.error(e);process.exit(1)});
