const fs=require('fs'),path=require('path');const {createCanvas,loadImage}=require('@napi-rs/canvas');const API=require('./preview-runtime.js');const ROOT=path.resolve(__dirname,'..');
(async()=>{const reg=JSON.parse(fs.readFileSync(path.join(ROOT,'assets/registry.json'))),images=new Map(),metas=new Map();for(const a of reg.assets)for(const v of a.render.variants)images.set(v.uri,await loadImage(path.join(ROOT,v.uri)));for(const r of reg.characters){images.set(r.uri,await loadImage(path.join(ROOT,r.uri)));metas.set(r.metadata,JSON.parse(fs.readFileSync(path.join(ROOT,r.metadata))));}
 for(const family of ['mini','big']){let scene=JSON.parse(fs.readFileSync(path.join(ROOT,'scenes',family+'.json'))),game=API.create(scene,new Map(reg.assets.map(a=>[a.assetId,a])));
  for(const sec of scene.sections){game.reset({x:sec.x,y:scene.spawn.y});game.update(.1,{});let snap=game.snapshot(),c=createCanvas(...scene.viewport);API.drawScene(c.getContext('2d'),scene,reg,images,metas,snap,{hero:'jane'});fs.writeFileSync(path.join(ROOT,'review',`${family}-${sec.id}.png`),c.toBuffer('image/png'));
   if(sec.id==='alley'){game.setDoor('open');snap=game.snapshot();API.drawScene(c.getContext('2d'),scene,reg,images,metas,snap,{hero:'jane'});fs.writeFileSync(path.join(ROOT,'review',`${family}-entrance-open.png`),c.toBuffer('image/png'));API.drawScene(c.getContext('2d'),scene,reg,images,metas,snap,{hero:'jane',geometry:true});fs.writeFileSync(path.join(ROOT,'review',`${family}-geometry.png`),c.toBuffer('image/png'));}}
  const c=createCanvas(scene.bounds.width,scene.viewport[1]);game.reset();API.drawScene(c.getContext('2d'),scene,reg,images,metas,game.snapshot(),{camera:0,staticActors:[{hero:'jane',x:scene.spawn.x,y:scene.spawn.y,state:'idle'},{hero:'jessie',x:scene.spawn.x+(family==='mini'?45:106),y:scene.spawn.y,state:'idle'},{hero:'jane',x:scene.approachSpawn.x,y:scene.spawn.y,state:'idle'},{hero:'jessie',x:scene.door.entryX-(family==='mini'?45:108),y:scene.spawn.y,state:'idle'}]});fs.writeFileSync(path.join(ROOT,'review',family+'-panorama.png'),c.toBuffer('image/png'));
  // Contact sheet: every asset at 1 native pixel, with UI labels outside the artwork.
  const list=reg.assets.filter(a=>a.family===family),cw=family==='mini'?228:356,ch=family==='mini'?176:288,cols=4,rows=Math.ceil(list.length/cols),sheet=createCanvas(cw*cols,ch*rows+60),ctx=sheet.getContext('2d');ctx.fillStyle='#121d19';ctx.fillRect(0,0,sheet.width,sheet.height);ctx.fillStyle='#d4ccad';ctx.font='20px sans-serif';ctx.fillText(`RECYKE / ${family.toUpperCase()} / native asset catalog`,18,33);
  list.forEach((a,i)=>{let x=i%cols*cw,y=Math.floor(i/cols)*ch+60;ctx.fillStyle='#20302a';ctx.fillRect(x+8,y+6,cw-16,ch-12);let img=images.get(a.render.variants[0].uri),w=a.native.width,h=a.native.height;ctx.drawImage(img,0,0,w,h,x+Math.floor((cw-w)/2),y+ch-49-h,w,h);ctx.fillStyle='#d4ccad';ctx.font='12px sans-serif';ctx.fillText(a.name,x+16,y+ch-30);ctx.fillStyle='#94aca0';ctx.font='11px monospace';ctx.fillText(`${w}×${h} · ${a.collision.decorative?'DECORATIVE':a.collision.defaults[0].kind}`,x+16,y+ch-14);});fs.writeFileSync(path.join(ROOT,'review',family+'-catalog.png'),sheet.toBuffer('image/png'));
 }
 console.log('Native panoramas, location previews, geometry captures and complete contact sheets rendered.');
})().catch(e=>{console.error(e);process.exit(1)});
