const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');const ROOT=path.resolve(__dirname,'..'),base=process.env.BASE_URL||'http://127.0.0.1:8056/recyke-kit/';
(async()=>{let browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run']}),errors=[],runs=[];
 for(const dpr of [1,2]){const context=await browser.newContext({viewport:{width:1440,height:1060},deviceScaleFactor:dpr});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});await page.goto(base);await page.waitForFunction(()=>window.KitPreview?.ready);
  for(const family of ['mini','big']){await page.locator(`[data-family=${family}]`).click();await page.locator('#scene').click();let start=await page.evaluate(()=>KitPreview.game.snapshot());await page.keyboard.down('KeyD');await page.waitForTimeout(650);await page.keyboard.down('KeyW');await page.waitForTimeout(180);let jumping=await page.evaluate(()=>KitPreview.game.snapshot());await page.keyboard.up('KeyW');await page.keyboard.up('KeyD');assert(jumping.player.x>start.player.x+25);assert(!jumping.player.onGround);await page.waitForTimeout(850);
   if(family==='mini'){await page.keyboard.down('KeyS');await page.waitForTimeout(70);let p=await page.evaluate(()=>KitPreview.game.snapshot().player);assert(p.crouching);assert.equal(p.hitbox.height,16);await page.keyboard.up('KeyS');}
   await page.keyboard.press('KeyP');let paused=await page.evaluate(()=>KitPreview.game.snapshot());await page.keyboard.down('KeyD');await page.waitForTimeout(100);assert.equal((await page.evaluate(()=>KitPreview.game.snapshot())).player.x,paused.player.x);await page.keyboard.up('KeyD');await page.keyboard.press('KeyP');
   await page.getByRole('button',{name:'03 / Concealed entrance'}).click();await page.keyboard.down('KeyD');let near=false;for(let i=0;i<50;i++){await page.waitForTimeout(70);let s=await page.evaluate(()=>({p:KitPreview.game.snapshot().player.x,door:KitPreview.scene.door}));if(s.p>s.door.entryX-s.door.interactionRadius+3){near=true;break;}}await page.keyboard.up('KeyD');assert(near);await page.waitForTimeout(100);for(let i=0;i<3;i++){await page.keyboard.press('KeyE');await page.waitForTimeout(60);}await page.waitForTimeout(850);assert((await page.evaluate(()=>KitPreview.game.snapshot())).won);
   const grid=await page.locator('#scene').evaluate(c=>({native:[c.width,c.height],css:[c.getBoundingClientRect().width,c.getBoundingClientRect().height],dpr:devicePixelRatio,smooth:c.getContext('2d').imageSmoothingEnabled}));assert(!grid.smooth);for(let i=0;i<2;i++)assert(Math.abs(grid.css[i]*grid.dpr/grid.native[i]-Math.round(grid.css[i]*grid.dpr/grid.native[i]))<.00001);
   if(dpr===1){await page.screenshot({path:path.join(ROOT,'review',`browser-${family}-scene.png`),fullPage:true});await page.locator('#geometry').check();await page.screenshot({path:path.join(ROOT,'review',`browser-${family}-geometry.png`),fullPage:true});await page.locator('#geometry').uncheck();}
   await page.locator('[data-tab=catalog]').click();await page.locator('#search').fill('concealed');assert.equal(await page.locator('.asset-card').count(),2);await page.getByRole('button',{name:/Concealed service entrance/}).click();await page.locator('#state').selectOption('opening');await page.waitForTimeout(300);if(dpr===1)await page.screenshot({path:path.join(ROOT,'review',`browser-${family}-catalog.png`),fullPage:true});await page.locator('#animate').uncheck();await page.locator('#frame').fill('6');assert.equal(await page.locator('#frame').inputValue(),'6');
   await page.locator('#search').fill('pipe');assert.equal(await page.locator('.asset-card').count(),3);await page.locator('#search').fill('nothere');assert.equal(await page.locator('.asset-card').count(),0);await page.locator('#search').fill('');await page.locator('#kind').selectOption('terrain');assert.equal(await page.locator('.asset-card').count(),16);await page.locator('#kind').selectOption('');await page.locator('[data-tab=demo]').click();await page.locator('#hero').selectOption('jessie');await page.locator('#reset').click();assert.equal((await page.evaluate(()=>KitPreview.game.snapshot())).doorState,'sealed');runs.push({family,dpr,keyboardMovement:true,jump:true,entranceCompleted:true,catalogSearchAndFrameControls:true,grid});
  }await context.close();
 }await browser.close();assert.deepEqual(errors,[]);fs.writeFileSync(path.join(ROOT,'review/browser-checks.json'),JSON.stringify({status:'passed',runs,errors},null,2)+'\n');console.log('Browser controls, catalog, entrance completion and native DPR grids passed for both families at DPR 1 and 2.');
})().catch(e=>{console.error(e);process.exit(1)});
