const assert=require('assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');const {loadImage,createCanvas}=require('@napi-rs/canvas');const API=require('../src/preview-runtime.js');const ROOT=path.resolve(__dirname,'..'),WORK=path.resolve(ROOT,'..'),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p))),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const reg=read('assets/registry.json'),ids=new Set(),assets=new Map(reg.assets.map(a=>[a.assetId,a])),palette=new Set(Object.values(reg.palette).map(c=>c.toLowerCase())),rasters=new Map();let frameCount=0,sheetCount=0,pixelCount=0;
 for(const a of reg.assets){assert(!ids.has(a.assetId),'duplicate ID');ids.add(a.assetId);for(const key of ['revision','name','kind','family','source','native','sockets','render','collision','properties','animation','tags','thumbnail','placement'])assert(key in a,key);assert(a.placement.allowScale===false);assert(a.render.scale===1);const {width:w,height:h,origin:o}=a.native;assert([w,h,...o].every(Number.isInteger));assert(w>0&&h>0);assert(a.family==='mini'||a.family==='big');
  for(const s of Object.values(a.animation.states)){assert.equal(s.frames.length,s.timingMs.length);assert(s.frames.every(f=>Number.isInteger(f)&&f>=0&&f<a.render.frameCount));assert(s.timingMs.every(t=>t>0));}
  for(const [vi,v] of a.render.variants.entries()){let bytes=fs.readFileSync(path.join(ROOT,v.uri));assert.equal(sha(bytes),v.sha256);let im=await loadImage(bytes);assert.equal(im.width,w*a.render.frameCount);assert.equal(im.height,h);let c=createCanvas(im.width,im.height),ctx=c.getContext('2d');ctx.drawImage(im,0,0);let px=ctx.getImageData(0,0,c.width,c.height).data;rasters.set(a.assetId+':'+vi,{px,w:c.width,h});sheetCount++;
   for(let i=0;i<px.length;i+=4){assert(px[i+3]===0||px[i+3]===255,`${a.assetId}: partial alpha`);if(px[i+3]){let hex='#'+[px[i],px[i+1],px[i+2]].map(n=>n.toString(16).padStart(2,'0')).join('');assert(palette.has(hex),`${a.assetId} color ${hex}`);pixelCount++;}}
   for(let f=0;f<a.render.frameCount;f++){let minX=w,minY=h,maxX=-1,maxY=-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=(y*c.width+x+f*w)*4;if(px[i+3]){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}}let b=a.native.visibleBounds.find(b=>b.frame===f&&b.variant===vi);assert.deepEqual(b,{variant:vi,frame:f,x:minX,y:minY,width:maxX-minX+1,height:maxY-minY+1});frameCount++;}
  }
 }
 let seamPairs=0,traversals=[];
 for(const family of ['mini','big']){let rule=reg.materialRules[family];assert.equal(Object.keys(rule.lookup).length,16);const pix=(r,x,y)=>Array.from(r.px.slice((y*r.w+x)*4,(y*r.w+x)*4+4));
  // All compatible horizontal street-edge pairings with matching U/D topology.
  for(let a=0;a<16;a++)for(let b=0;b<16;b++)if((a&2)&&(b&8)&&((a&5)===(b&5))){for(let v=0;v<3;v++){let ar=rasters.get(rule.lookup[a]+':'+v),br=rasters.get(rule.lookup[b]+':'+(v+1)%3);for(let y=0;y<ar.h;y++)assert.deepEqual(pix(ar,ar.w-1,y),pix(br,0,y),`${family} street seam ${a}/${b} row ${y}`);seamPairs++;}}
  let scene=read(`scenes/${family}.json`),instanceIds=new Set();for(const e of scene.entities){assert(!instanceIds.has(e.id));instanceIds.add(e.id);let a=assets.get(e.assetId);assert(a&&a.family===family);assert(Number.isInteger(e.x)&&Number.isInteger(e.y));assert(e.variant<a.render.variants.length);assert(!('scale' in e));}assert(instanceIds.has(scene.door.entityId));
  let sim=API.create(scene,assets),snap=sim.snapshot();sim.pause(true);sim.update(.1,{right:true});assert.equal(sim.snapshot().player.x,snap.player.x);sim.pause(false);if(family==='mini'){sim.update(1/120,{down:true});assert.equal(sim.snapshot().player.hitbox.height,16);sim.update(1/120,{});assert.equal(sim.snapshot().player.hitbox.height,30);}
  let jumpLatch=false,t=0,lastX=0,stale=0,visitedRaised=false;sim.reset();while(t<90){let p=sim.snapshot().player,go=p.x<scene.door.entryX-3;let jump=go&&p.onGround&&!jumpLatch;jumpLatch=jump;sim.update(1/120,{right:go,jump});snap=sim.snapshot();t+=1/120;visitedRaised||=snap.player.onGround&&snap.player.y<scene.spawn.y;if(Math.abs(snap.player.x-lastX)<.0001)stale++;else stale=0;lastX=snap.player.x;if(!go&&snap.player.onGround)break;if(stale>600)throw Error(`${family} stuck x${lastX} y${snap.player.y}`);}
  assert(t<90);assert(visitedRaised,'Never landed on raised geometry');assert(Math.abs(snap.player.y-scene.door.entryY)<1);assert(sim.interact());assert.equal(sim.snapshot().doorState,'latched');assert(sim.interact());assert.equal(sim.snapshot().doorState,'unlatched');assert(sim.interact());for(let i=0;i<100;i++)sim.update(1/120,{});assert(sim.snapshot().won);assert.equal(sim.snapshot().doorState,'open');traversals.push({family,seconds:Number(t.toFixed(2)),input:'right + discrete grounded jumps; 3 entrance inspections',visitedRaised:true,completed:true});
  let d=assets.get(`cad.${family}.recyke.concealed-door`);assert.equal(API.frameAt(d,'opening',99),6,'nonloop holds final open');assert.equal(d.collision.defaults[0].kind,'sensor');
 }
 for(const r of reg.characters){assert.equal(sha(fs.readFileSync(path.join(ROOT,r.uri))),r.sha256);assert.equal(sha(fs.readFileSync(path.join(WORK,r.source))),r.sha256,'hero source changed');let meta=read(r.metadata);assert.deepEqual(meta.sizes[r.family].anchor,r.anchor);assert.equal(meta.sizes[r.family].width,r.cell[0]);}
 const protectedFiles=read('reference/protected-files-before.json'),changes=[];for(const [file,hash] of Object.entries(protectedFiles))if(!fs.existsSync(path.join(WORK,file))||sha(fs.readFileSync(path.join(WORK,file)))!==hash)changes.push(file);assert.deepEqual(changes,[],'Protected source files changed');
 const checks={status:'passed',definitions:reg.assets.length,nativeSheets:sheetCount,authoredFrameVariantRasters:frameCount,opaquePixelsChecked:pixelCount,compatibleStreetSeamPairs:seamPairs,protectedFilesUnchanged:Object.keys(protectedFiles).length,approvedCharacterSheetsUnchanged:reg.characters.length,traversals,limits:['Traversal harness, not campaign combat simulation.','Bounds checks run during generation against a padded canvas.','Art judgment requires the accompanying visual review.']};fs.writeFileSync(path.join(ROOT,'review/checks.json'),JSON.stringify(checks,null,2)+'\n');console.log(JSON.stringify(checks,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
