const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert');const root=path.resolve(__dirname,'..');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});const results=[];for(const dpr of[1,2]){const page=await browser.newPage({viewport:{width:1500,height:980},deviceScaleFactor:dpr,acceptDownloads:true});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await page.goto('http://127.0.0.1:8056/episode-one/');await page.waitForFunction(()=>window.EP1App);await page.evaluate(()=>{EP1App.loadLevel('03a-secondary');EP1App.mission.skipSequence();});await page.locator('#canvas').focus();const start=await page.evaluate(()=>EP1App.mission.state().world.player.x);await page.keyboard.down('d');await page.waitForTimeout(400);await page.keyboard.up('d');assert((await page.evaluate(()=>EP1App.mission.state().world.player.x))>start+15);await page.keyboard.down('s');await page.waitForTimeout(80);assert(await page.evaluate(()=>EP1App.mission.state().world.player.crouching));await page.keyboard.down(' ');await page.waitForTimeout(80);assert(await page.evaluate(()=>EP1App.mission.state().world.player.state.includes('fire')));await page.keyboard.up(' ');await page.keyboard.up('s');await page.keyboard.press('Escape');const px=await page.evaluate(()=>EP1App.mission.state().world.player.x);await page.keyboard.down('d');await page.waitForTimeout(100);await page.keyboard.up('d');assert.equal(await page.evaluate(()=>EP1App.mission.state().world.player.x),px);await page.keyboard.press('Escape');await page.keyboard.press('w');await page.waitForTimeout(110);assert(await page.evaluate(()=>EP1App.mission.state().world.player.y<222));await page.screenshot({path:root+`/review/combat-dpr${dpr}.png`});const grid=await page.evaluate(()=>{const r=canvas.getBoundingClientRect();return{scale:r.width*devicePixelRatio/canvas.width,x:r.left*devicePixelRatio,y:r.top*devicePixelRatio};});assert(Math.abs(grid.scale-Math.round(grid.scale))<.001);assert(Math.abs(grid.x-Math.round(grid.x))<.001);
 await page.evaluate(()=>{EP1App.loadLevel('05-reaching-out');EP1App.mission.skipSequence();});await page.locator('#canvas').focus();await page.keyboard.down('w');await page.keyboard.down(' ');await page.waitForTimeout(250);await page.keyboard.up('w');await page.keyboard.up(' ');assert(await page.evaluate(()=>EP1App.mission.state().world.player.y<120));
 await page.evaluate(()=>{EP1App.loadLevel('03a-secondary');EP1App.enterEditor();});await page.waitForTimeout(150);const baseline=await page.evaluate(()=>JSON.stringify(EP1App.editor.draft));await page.locator('#asset-search').fill('terminal');await page.locator('.asset[title="cad.mini.episode1.terminal"]').click();const loc=await page.evaluate(()=>{const e=EP1App.editor,c=document.querySelector('#canvas'),r=c.getBoundingClientRect();return{x:r.left+(215-e.camera.x)*r.width/c.width,y:r.top+(160-e.camera.y)*r.height/c.height};});await page.mouse.click(loc.x,loc.y);assert.equal(await page.evaluate(()=>EP1App.editor.selection.size),1);const count=await page.evaluate(()=>EP1App.editor.draft.entities.length);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),baseline);await page.locator('#redo').click();assert.equal(await page.evaluate(()=>EP1App.editor.draft.entities.length),count);
 await page.keyboard.press('Escape');await page.locator('.hierarchy-item').filter({hasText:'Interactive control console · asset'}).first().click();await page.locator('#canvas').focus();await page.keyboard.press('Control+d');assert.equal(await page.evaluate(()=>EP1App.editor.draft.entities.length),count+1);await page.keyboard.press('Control+z');assert.equal(await page.evaluate(()=>EP1App.editor.draft.entities.length),count);
 await page.locator('[data-tool="paint"]').click();const paintBefore=await page.evaluate(()=>EP1App.editor.draft.terrain.length);const paintLoc=await page.evaluate(()=>{const e=EP1App.editor,c=document.querySelector('#canvas'),r=c.getBoundingClientRect();return{x:r.left+(260-e.camera.x)*r.width/c.width,y:r.top+(120-e.camera.y)*r.height/c.height};});await page.mouse.move(paintLoc.x,paintLoc.y);await page.mouse.down();await page.mouse.move(paintLoc.x+150,paintLoc.y,{steps:8});await page.mouse.up();assert((await page.evaluate(()=>EP1App.editor.draft.terrain.length))>paintBefore);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>EP1App.editor.draft.terrain.length),paintBefore);
 await page.locator('[data-panel="sequence"]').click();await page.locator('textarea[aria-label="Text"]').fill('Edited prototype line for round-trip verification.');await page.locator('textarea[aria-label="Text"]').press('Tab');const draft=await page.evaluate(()=>JSON.stringify(EP1App.editor.draft));await page.locator('#play-test').click();assert.equal(await page.evaluate(()=>EP1App.mode),'test');await page.locator('#stop-test').click();assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),draft);
 const aligned=await page.evaluate(()=>EP1App.editor.snapped({x:48,y:222}).y);assert.equal(aligned,222);const downloadPromise=page.waitForEvent('download');await page.locator('textarea[aria-label="Text"]').focus();await page.keyboard.press('Control+s');const download=await downloadPromise;const filepath=root+`/review/export-test-dpr${dpr}.json`;await download.saveAs(filepath);assert.equal(JSON.stringify(JSON.parse(fs.readFileSync(filepath))),draft);await page.locator('#file-input').setInputFiles(filepath);assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),draft);
 await page.evaluate(()=>EP1App.editor.autosave());await page.locator('#recovery').click();await page.locator('#recovery-list button').first().waitFor({state:'visible'});assert((await page.locator('#recovery-list button').count())>0);await page.locator('#recovery-list button').first().click();assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),draft);
 for(let i=0;i<10;i++){await page.evaluate(()=>{EP1App.playtest();EP1App.backToEditor();});}assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),draft);
 await page.reload();await page.waitForFunction(()=>window.EP1App);await page.evaluate(()=>{EP1App.loadLevel('03a-secondary');EP1App.enterEditor();});await page.locator('#recovery').click();await page.locator('#recovery-list button').first().waitFor({state:'visible'});await page.locator('#recovery-list button').first().click();assert.equal(await page.evaluate(()=>JSON.stringify(EP1App.editor.draft)),draft);
 const malformed=await page.evaluate(()=>{const before=JSON.stringify(EP1App.editor.draft);let caught=false;try{EP1App.editor.import({...EP1App.editor.draft,layers:'bad'});}catch{caught=true;}return caught&&before===JSON.stringify(EP1App.editor.draft);});assert(malformed);
 // Restore original document for clean visual review.
 await page.evaluate(async()=>{const l=await(await fetch('levels/03a-secondary.json')).json();EP1App.editor.open(l);EP1App.editor.panel='sequence';EP1App.editor.sequenceId='opening';EP1App.editor.cardIndex=0;EP1App.editor.renderInspector();});await page.waitForTimeout(100);await page.screenshot({path:root+`/review/workshop-dpr${dpr}.png`});
 if(dpr===1){for(const row of await page.evaluate(()=>EP1App.manifest.levels)){await page.evaluate(id=>{EP1App.loadLevel(id);EP1App.mission.skipSequence();EP1App.mission.pause(true);EP1App.fit();},row.id);await page.evaluate(()=>{const m=EP1App.mission,s=EP1Data.clone(m.state());s.world.enemies.forEach(e=>e.enabled=true);const x=m.level.mode==='flight'?(m.level.chapter===5?1100:1750):m.level.chapter===1?960:m.level.chapter===10?170:Math.min(380,m.level.bounds.width-480);s.world.player.x=x+85;s.world.player.y=m.level.mode==='flight'?135:222;s.hiddenPlayer=false;EP1Render.draw(document.getElementById('canvas').getContext('2d'),m.level,s,{camera:{x,y:0},markers:true,mission:m});window.captureForReview=document.getElementById('canvas').toDataURL('image/png');});const uri=await page.evaluate(()=>window.captureForReview);fs.writeFileSync(root+'/review/'+row.id+'.png',Buffer.from(uri.split(',')[1],'base64'));}}
 assert.deepEqual(errors,[]);results.push({dpr,grid,errors,keyboard:true,paintUndo:true,dialogueEdit:true,saveOpen:true,recovery:true,recoveryAfterReload:true,playtestIsolation:10});await page.close();}
fs.writeFileSync(root+'/review/browser-checks.json',JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));await browser.close();})();
