'use strict';const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const p=await browser.newPage({viewport:{width:1280,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install();const url=(process.env.BASE_URL||'http://127.0.0.1:8042/recyke-development')+'/recyke.html';const snap=()=>p.evaluate(()=>CADRecykeApp.snapshot()),step=ms=>p.clock.runFor(ms);
for(const hero of ['jane','jessie']){await p.goto(url+'?hero='+hero);await p.waitForFunction(()=>window.CADRecykeApp);await p.locator('#game-canvas').focus();
 await p.keyboard.down('s');await step(64);let s=await snap();assert.equal(s.player.hitbox.h,16);assert.equal(s.player.state,'crouch-idle');const feet=s.player.y;
 await p.keyboard.down('d');await step(300);s=await snap();assert.equal(s.player.state,'crouch-walk');assert.equal(s.player.y,feet);assert.equal(s.player.vx,25);
 await p.keyboard.down('Space');await step(100);s=await snap();assert.equal(s.player.state,'crouch-walk-fire');assert.equal(s.player.hitbox.h,16);assert(s.shots.some(x=>!x.hostile));
 await p.keyboard.up('d');await step(120);s=await snap();assert.equal(s.player.state,'crouch-fire');await p.locator('#game-stage').screenshot({path:path.resolve(__dirname,'../../mini-review/assets/'+hero+'-crouch-game.png')});
 await p.keyboard.up('s');await step(64);s=await snap();assert.equal(s.player.hitbox.h,30);assert.equal(s.player.state,'fire');await p.keyboard.up('Space');
 await p.keyboard.down('ArrowDown');await step(64);assert.equal((await snap()).player.hitbox.h,16);await p.keyboard.press('q');await step(32);assert.equal((await snap()).player.hitbox.h,16);
 await p.locator('#pause-button').click();await p.keyboard.up('ArrowDown');await p.locator('#dialog-primary').click();await step(64);assert.equal((await snap()).player.hitbox.h,30,'resume clears held duck');
 await p.keyboard.down('s');await step(64);await p.locator('#restart-button').click();await p.keyboard.up('s');await step(64);assert.equal((await snap()).player.hitbox.h,30,'restart clears crouch');
}
const context=await browser.newContext({viewport:{width:844,height:620},isMobile:true,hasTouch:true,deviceScaleFactor:2});const touch=await context.newPage();touch.on('pageerror',e=>errors.push(e.message));await touch.clock.install();await touch.goto(url);await touch.waitForFunction(()=>window.CADRecykeApp);const session=await context.newCDPSession(touch);const coords={};for(const[action,id]of [['down',1],['right',2],['fire',3]]){const b=await touch.locator(`[data-control="${action}"]`).boundingBox();assert(b);coords[action]={id,x:b.x+b.width/2,y:b.y+b.height/2,radiusX:3,radiusY:3,force:1};}
await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[coords.down,coords.right,coords.fire]});await touch.clock.runFor(250);let s=await touch.evaluate(()=>CADRecykeApp.snapshot());assert.equal(s.player.state,'crouch-walk-fire');assert.equal(s.player.hitbox.h,16);
await session.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await touch.clock.runFor(300);s=await touch.evaluate(()=>CADRecykeApp.snapshot());assert.equal(s.player.hitbox.h,30);assert.equal(s.player.vx,0);assert(!s.player.state.includes('fire'));
assert.deepEqual(errors,[]);await context.close();console.log('PASS crouch browser: both heroes, S/Down, move+fire, release, swap, pause/restart and three-touch duck/move/fire/cancel; no JS errors.');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
