'use strict';const{chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:8042/mini-review/');await page.locator('#pause').click();assert.equal(await page.locator('#sequences canvas').count(),32);
 assert.equal(await page.locator('#moves').inputValue(),'crouch');await page.selectOption('#moves','normal');await page.selectOption('#moves','crouch');await page.locator('#hitboxes').uncheck();await page.locator('#hitboxes').check();
 const initial=await page.locator('#comparison').evaluate(c=>c.toDataURL());await page.locator('#step').click();await page.locator('#step').click();assert.notEqual(await page.locator('#comparison').evaluate(c=>c.toDataURL()),initial);
 for(const actor of ['jane','jessie']){await page.selectOption('#actor',actor);const states=await page.locator('#action option').evaluateAll(o=>o.map(x=>x.value));assert.equal(states.length,actor==='jane'?18:14);for(const state of states){await page.selectOption('#action',state);await page.locator('#pose-step').click();assert.match(await page.locator('#pose-label').textContent(),/^2 \/ /);}}
 for(const e of ['sentinel','bastion','scrapper','watcher','manta','collector']){await page.selectOption('#enemy',e);await page.locator('#enemy-step').click();assert.match(await page.locator('#enemy-label').textContent(),/^2 \/ /);}
 await page.selectOption('#facing','-1');await page.selectOption('#background','light');await page.locator('#silhouette').check();await page.locator('#stage').screenshot({path:__dirname+'/assets/browser-left-silhouettes.png'});
 await page.locator('#silhouette').uncheck();await page.locator('#stage').screenshot({path:__dirname+'/assets/browser-left-light.png'});
 await page.selectOption('#facing','1');await page.selectOption('#background','dark');await page.screenshot({path:__dirname+'/assets/browser-desktop.png'});
 for(const d of ['jane-development','jessie-refinement','enemy-development','recyke-development']){
  await page.goto('http://127.0.0.1:8042/'+d+'/codex.html');await page.waitForTimeout(100);assert.equal(await page.locator('[data-asset$="-big"]').count(),0);assert.match(await page.locator('#assetName').textContent(),/Mini/);const size=await page.locator('#art').evaluate(c=>[c.width,c.height]);assert.deepEqual(size,[48,48]);
  await page.goto('http://127.0.0.1:8042/'+d+'/codex.html#jane-big');await page.waitForTimeout(100);if(d!=='jessie-refinement')assert.equal(await page.locator('#assetName').textContent(),'Jane / Mini');
 }
 await page.goto('http://127.0.0.1:8042/recyke-development/recyke.html');await page.waitForFunction(()=>window.CADRecykeApp);assert.equal(await page.evaluate(()=>CADRecykeApp.snapshot().size),'mini');assert.equal(await page.locator('[data-size="big"]').count(),0);
 for(const dpr of [1,3]){const phone=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:dpr});phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://127.0.0.1:8042/mini-review/');const v=await phone.evaluate(()=>{const c=document.querySelector('#comparison'),r=c.getBoundingClientRect();return{scale:r.width*devicePixelRatio/c.width,width:document.documentElement.scrollWidth,viewport:innerWidth,smoothing:c.getContext('2d').imageSmoothingEnabled};});assert(Math.abs(v.scale-Math.round(v.scale))<.001);assert(v.width<=v.viewport);assert(!v.smoothing);if(dpr===3)await phone.screenshot({path:__dirname+'/assets/browser-mobile.png'});await phone.close();}
 assert.deepEqual(errors,[]);console.log('PASS mini workshop: 32 hero action strips, pose stepping, six enemies, facings/backgrounds/silhouettes, four mini catalogues, mini game default, desktop/mobile grids; no JS errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
