const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createCanvas}=require('@napi-rs/canvas');const box={window:{},document:{createElement:()=>createCanvas(1,1)}};vm.createContext(box);for(const n of ['jane-motion','jessie-motion','jane','jessie']){vm.runInContext(fs.readFileSync(path.join(__dirname,'../recyke-development',n+'.js'),'utf8'),box);Object.assign(box,box.window);}
const states=['crouch-idle','crouch-walk','crouch-fire','crouch-walk-fire'],cv=createCanvas(576,8*62),c=cv.getContext('2d');c.fillStyle='#34434b';c.fillRect(0,0,cv.width,cv.height);
for(const [i,name]of ['Jane','Jessie'].entries()){const A=box['CAD'+name];states.forEach((state,j)=>{const y=(i*4+j)*62;c.fillStyle='#d6e0d1';c.font='9px sans-serif';c.fillText(name+' / '+state,5,y+11);for(let f=0;f<A.durations[state].length;f++)A.draw(c,'mini',f*48+20,y+52,{state,frame:f});});}
const out=createCanvas(cv.width*2,cv.height*2),g=out.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(cv,0,0,out.width,out.height);fs.writeFileSync(path.join(__dirname,'assets/crouch-sequences.png'),out.toBuffer('image/png'));

vm.runInContext(fs.readFileSync(path.join(__dirname,'scene.js'),'utf8'),box);const stage=createCanvas(480,184),sc=stage.getContext('2d');box.window.CADMiniScene.draw(sc,{time:.24,crouch:true,hitboxes:true,travel:false});const zoom=createCanvas(1440,552),zc=zoom.getContext('2d');zc.imageSmoothingEnabled=false;zc.drawImage(stage,0,0,1440,552);fs.writeFileSync(path.join(__dirname,'assets/crouch-comparison.png'),zoom.toBuffer('image/png'));

fs.mkdirSync('/private/tmp/crouch-frames',{recursive:true});for(let f=0;f<96;f++){box.window.CADMiniScene.draw(sc,{time:f*.05,crouch:true,travel:true});zc.drawImage(stage,0,0,1440,552);fs.writeFileSync(`/private/tmp/crouch-frames/${String(f).padStart(3,'0')}.png`,zoom.toBuffer('image/png'));}
c.fillStyle='#d8dedb';c.fillRect(0,0,cv.width,cv.height);for(const[i,name]of ['Jane','Jessie'].entries()){const A=box['CAD'+name];states.forEach((state,j)=>{const y=(i*4+j)*62;c.fillStyle='#263942';c.font='9px sans-serif';c.fillText(name+' / '+state,5,y+11);for(let f=0;f<A.durations[state].length;f++)A.draw(c,'mini',f*48+26,y+52,{state,frame:f,facing:-1});});}g.drawImage(cv,0,0,out.width,out.height);fs.writeFileSync(path.join(__dirname,'assets/crouch-sequences-left.png'),out.toBuffer('image/png'));
