(() => {'use strict';const $=id=>document.getElementById(id),canvas=$('comparison'),c=canvas.getContext('2d');let time=0,last=performance.now(),paused=false,pose=0,enemyPose=0;const models={jane:CADJane,jessie:CADJessie};
const light=()=>$('background').value==='light',face=()=>Number($('facing').value);
function resize(){const dpr=devicePixelRatio||1;for(const cv of document.querySelectorAll('canvas')){const scale=cv.id==='comparison'?Math.max(1,Math.round(2*dpr)):Math.max(1,Math.round(3*dpr));const info=CADPixelGrid.applyScene(cv,{...(cv.id==='comparison'?{availableWidth:cv.parentElement.clientWidth-24,maxScale:Math.max(2,Math.round(3*dpr))}:{scale}),});if(cv.id==='comparison')$('grid-note').textContent=`One source pixel = ${info.scale} device pixels · Uniform zoom for the complete scene · No smoothing`;}}
function background(cv){const ctx=cv.getContext('2d');ctx.fillStyle=light()?'#d8dedb':'#202c36';ctx.fillRect(0,0,cv.width,cv.height);return ctx;}
function drawModel(ctx,A,x,y,o){if(!$('silhouette').checked){A.draw(ctx,'mini',x,y,o);return;}const layer=document.createElement('canvas');layer.width=ctx.canvas.width;layer.height=ctx.canvas.height;const g=layer.getContext('2d');A.draw(g,'mini',x,y,o);g.globalCompositeOperation='source-in';g.fillStyle=light()?'#192a36':'#e2e8de';g.fillRect(0,0,layer.width,layer.height);ctx.drawImage(layer,0,0);}
function strip(cv,A,state){cv.width=A.durations[state].length*48;cv.height=62;const g=background(cv);for(let f=0;f<A.durations[state].length;f++){drawModel(g,A,f*48+20,40,{state,frame:f,facing:face()});g.fillStyle=light()?'#30414b':'#aebfc8';g.font='8px monospace';g.fillText(`${f+1} ${A.durations[state][f]}ms`,f*48+2,57);}}
function sequences(){const root=$('sequences');root.replaceChildren();for(const[name,A]of Object.entries(models)){const d=document.createElement('details');d.open=true;const summary=document.createElement('summary');summary.textContent=`${name==='jane'?'Jane':'Jessie'} · All ${A.states.length} actions`;d.append(summary);const content=document.createElement('div');content.className='content';for(const state of A.states){const h=document.createElement('h3');h.textContent=state+' / '+A.durations[state].length+' poses';const wrap=document.createElement('div');wrap.className='strip';const cv=document.createElement('canvas');cv.dataset.actor=name;cv.dataset.state=state;cv.setAttribute('aria-label',name+' '+state+' complete sequence');wrap.append(cv);content.append(h,wrap);strip(cv,A,state);}d.append(content);root.append(d);}enemyStrip();resize();}
function choose(){pose=0;const A=models[$('actor').value];$('action').replaceChildren(...A.states.map(s=>new Option(s,s)));paintSolo();}
function paintSolo(){const A=models[$('actor').value],state=$('action').value,frame=paused?pose%A.durations[state].length:A.frameAt(state,time),g=background($('solo'));drawModel(g,A,60,56,{state,frame,facing:face()});$('pose-label').textContent=`${frame+1} / ${A.durations[state].length} · ${A.durations[state][frame]}ms`;}
function enemyStrip(){const A=CADEnemies.adapter($('enemy').value),state=$('enemy-action').value;if(state)strip($('enemy-strip'),A,state);}
function chooseEnemy(){enemyPose=0;const A=CADEnemies.adapter($('enemy').value);$('enemy-action').replaceChildren(...A.states.map(s=>new Option(s,s)));enemyStrip();resize();}
function paintEnemy(){const A=CADEnemies.adapter($('enemy').value),state=$('enemy-action').value,frame=paused?enemyPose%A.durations[state].length:A.frameAt(state,time),g=background($('enemy-preview'));drawModel(g,A,60,56,{state,frame,facing:face()});$('enemy-label').textContent=`${frame+1} / ${A.durations[state].length}`;}
function paint(){CADMiniScene.draw(c,{time,facing:face(),light:light(),silhouette:$('silhouette').checked,travel:$('travel').checked,crouch:$('moves').value==='crouch',hitboxes:$('hitboxes').checked});paintSolo();paintEnemy();}
function pause(value){paused=value;$('pause').textContent=value?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(value));}
$('pause').onclick=()=>pause(!paused);$('step').onclick=()=>{pause(true);time+=.05;paint();};$('pose-step').onclick=()=>{pause(true);pose++;paintSolo();};$('enemy-step').onclick=()=>{pause(true);enemyPose++;paintEnemy();};$('actor').onchange=choose;$('action').onchange=()=>{pose=0;time=0;paint();};$('enemy').onchange=chooseEnemy;$('enemy-action').onchange=()=>{enemyPose=0;enemyStrip();paint();resize();};
for(const id of ['facing','background','silhouette'])$(id).onchange=()=>{sequences();paint();};$('travel').onchange=paint;$('hitboxes').onchange=paint;$('moves').onchange=()=>{time=0;paint();};
$('enemy').replaceChildren(...CADEnemies.entries.map(e=>new Option(e.name,e.id)));chooseEnemy();choose();sequences();
const focus=new URLSearchParams(location.search).get('focus');if(focus==='jessie'){$('actor').value='jessie';choose();}
window.addEventListener('resize',resize);function tick(now){if(!paused&&!document.hidden)time+=Math.min(.05,Math.max(0,(now-last)/1000))*Number($('speed').value);last=now;paint();requestAnimationFrame(tick);}paint();requestAnimationFrame(tick);
})();
