/* Authored prototype layouts. Regenerate intentionally; never runs in the editor. */
const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');const N=k=>'cad.mini.episode1.'+k,R=k=>'cad.mini.recyke.'+k;const levels=[];let uid=0;
const entity=(l,kind,x,y,asset,key,props={})=>{const e={id:key||`${kind}-${++uid}`,name:key?.replaceAll('-',' ')||kind,kind,x,y,layer:['enemy','npc'].includes(kind)?'actors':['solid','platform','hazard'].includes(kind)?'playable':'scenery',...(asset?{assetId:asset,assetRevision:1}:{}),...props};l.entities.push(e);return e;};
const say=(speaker,text,source='prototype')=>({type:'dialogue',speaker,text,source,duration:Math.max(2400,Math.min(6500,text.length*42))});
const move=(actor,x,y,duration=2200)=>({type:'move',actor,x,y,duration});const camera=(x,y=0,duration=1500)=>({type:'camera',x,y,duration});const title=(text,duration=2200)=>({type:'title',text,duration});const flag=name=>({type:'flag',flag:name,value:true,duration:1});
function base(id,chapter,titleText,theme,width=1440,hero='jane',mode='ground'){uid=0;let l={schemaVersion:1,assetPack:'cad.episode1.prototype@1',id,chapter,title:titleText,sourceTitle:chapter===6||chapter===9?null:titleText,status:'playable-prototype',dialogueStatus:'Supplied oath exact; other dialogue provisional.',family:'mini',mode,theme,bounds:{width,height:270},viewport:[480,270],spawn:{x:48,y:222,hero},physicsProfile:mode==='flight'?'cad.mini.flight.prototype-v1':'cad.mini.ground.approved-v1',layers:[{id:'distant',order:0},{id:'architecture',order:10},{id:'scenery',order:20},{id:'playable',order:30},{id:'actors',order:40},{id:'foreground',order:50}],terrainOrigin:{x:0,y:6},terrain:[],entities:[],objectives:[],sequences:{},onStart:null,onComplete:null,timer:null,notes:[]};
 if(mode==='ground'){entity(l,'solid',0,222,N(theme==='skyview'?'stone-floor':'steel-floor'),'floor',{w:width,h:48});for(let x=0;x<width;x+=192)entity(l,'decor',x,170,R('skyline'),null,{layer:'distant',variant:(x/192)%2});
 const wall=theme==='recyke'?R('facade'):N(theme==='skyview'?'skyview-window':theme==='hideout'?'hideout-wall':theme==='ruin'?'hub-wall':theme==='server'?'server-wall':'hub-wall');
 for(let x=0;x<width;x+=64){entity(l,'decor',x,222,wall,null,{layer:'architecture',variant:theme==='recyke'?(x/64)%3:0});if(x%192===0)entity(l,'decor',x,110,R('roof'),null,{layer:'architecture',variant:Math.floor(x/192)%3});}
 } else{l.spawn={x:85,y:135,hero:'jane'};l.flight={speed:100,steerSpeed:145,finishX:width-220};for(let x=0;x<width;x+=192)entity(l,'decor',x,264,R('skyline'),null,{layer:'distant',variant:(x/192)%2});}
 levels.push(l);return l;}
function seq(l,id,cards){l.sequences[id]={id,name:id.replaceAll('-',' '),cards};return id;}
function objective(l,id,label,requires){l.objectives.push({id,label,requires});}
function terminal(l,x,id,label,requires=[],sequence=null){return entity(l,'terminal',x,222,N('terminal'),id,{label,flag:id,requires,sequence});}
function checkpoint(l,x,y=222){return entity(l,'checkpoint',x,y,N('checkpoint'),'checkpoint-'+x,{label:'Repair & checkpoint'});}
function pickup(l,x,y=204,type='health'){return entity(l,'pickup',x,y,N(type),null,{pickup:type});}
function enemy(l,x,y=222,type='sentinel',hp=3,opts={}){return entity(l,'enemy',x,y,null,opts.id||null,{archetype:type,hp,left:x-24,right:x+24,facing:-1,activationX:Math.max(0,x-380),...opts});}
function platform(l,x,y,n=4){for(let i=0;i<n;i++)entity(l,'platform',x+i*24,y,R(i===0?'catwalk-left':i===n-1?'catwalk-right':'catwalk-middle'),null,{w:24,h:6});entity(l,'decor',x+12,y+40,R('support'),null);}
function crate(l,x,tall=false){return entity(l,'asset',x,222,R(tall?'crate-tall':'crate-low'),null,{layer:'playable'});}
function exit(l,x,requires=[],sequence=null,y=222,asset='blast-door'){return entity(l,'exit',x,y,N(asset),'exit',{label:asset==='cruiser'?'Board cruiser':'Continue',requires,sequence});}
function trigger(l,x,sequence,key,requires=[]){return entity(l,'trigger',x,160,null,key,{w:40,h:70,sequence,requires,once:true});}
function hazard(l,x,y=222){return entity(l,'hazard',x,y,N('hazard'),null,{w:48,h:12,period:3,onDuration:1.35,damage:1});}
function intro(l,cards){l.onStart=seq(l,'opening',cards);}
// 01 — authored opening uses kit geometry but scripted staging, not the kit's toy interaction.
let l=base('01-intro',1,'Intro','recyke');const kit=JSON.parse(fs.readFileSync(path.join(root,'../recyke-kit/scenes/mini.json')));l.entities=kit.entities.map(e=>({...e,kind:'asset',name:e.id}));l.spawn.x=70;l.entities.push({id:'jessie',name:'Jessie',kind:'npc',hero:'jessie',x:100,y:222,layer:'actors'});
intro(l,[say('Jessie','You picked a good night. The presses almost drown out my terrible directions.'),say('Janey','Almost. You said the entrance was impossible to miss.'),move('player',370,222,3300),move('jessie',400,222,2600),camera(380),say('Jessie','It is. Once someone shows you where it isn’t.'),move('player',1060,222,4000),move('jessie',1100,222,3600),camera(960),move('player',1350,222,2200),move('jessie',1385,222,2200),say('Jessie','[Password exchange — original wording not supplied.]','missing-source'),{type:'object',target:kit.door.entityId,state:'latched',duration:350},{type:'object',target:kit.door.entityId,state:'unlatched',duration:350},{type:'object',target:kit.door.entityId,state:'opening',duration:900},move('jessie',1390,222,500),{type:'visibility',actor:'jessie',visible:false,duration:1},move('player',1390,222,500),{type:'visibility',actor:'player',visible:false,duration:1},camera(960,-110,2600),title('CTRL ALT DEL',3000),title('EPISODE I',2200),{type:'complete',duration:1}]);l.notes.push('Password and album cues remain explicitly missing. New banter is provisional.');
// 02 — social opening, then a compact, optional-to-story tutorial route.
l=base('02-moral-code',2,'The Moral Code','hideout',1296);entity(l,'decor',8,222,N('elevator'),'elevator',{layer:'architecture'});entity(l,'npc',100,222,null,'jessie',{hero:'jessie'});entity(l,'npc',232,222,N('hooded-leader'),'leader');for(const x of [300,360,430])entity(l,'npc',x,222,N('operative'));for(const x of[350,650,1030])entity(l,'decor',x,222,N('desk'));entity(l,'decor',470,154,N('broadcast'));entity(l,'decor',535,222,R('puddle'));entity(l,'decor',630,100,R('pipe-horizontal'));
intro(l,[camera(0,-35,1),say('Janey','Does this lift always sound like it’s negotiating with gravity?'),camera(0,0,2200),say('Jessie','Every time. It hasn’t lost an argument yet.'),say('Leader','Recruit! Step forward.','source')]);
const oath=seq(l,'oath',[say('Leader','Do swear to do no harm unless absolutely necessary?','source'),say('Janey','I Do','source'),say('Leader','Do you promise to uphold the code, and understand it may be hard to carry?','source'),say('Janey','I Do!','source'),say('Leader','Do you swear to upload the code if given access, and by doing so, destroy the Nexis?','source'),title('The music swells. Acceptance is implied.\n[Album recording / lyrics pending.]',3500),flag('oath'),say('Jessie','The practice lane is clear. Jump the crates, use the console, then hit the training unit. E to interact; Space to fire; F to strike.')]);terminal(l,210,'approach','Approach the leader',[],oath);crate(l,500);crate(l,550,true);platform(l,590,178,5);pickup(l,650,164,'shield');terminal(l,760,'training-console','Activate training lane',['oath']);enemy(l,930,222,'sentinel',3,{id:'training-unit',passive:true});checkpoint(l,1050);objective(l,'join','Take the oath',['oath']);objective(l,'learn','Activate the practice console and disable the training unit',['training-console','dead:training-unit']);exit(l,1200,['oath','training-console','dead:training-unit'],seq(l,'welcome',[say('Leader','Welcome Recruit, to The Moral Code!','source')]));l.notes.push('Training is the optional suggestion from the outline. Symbol omitted pending design.');
// 03A — Jessie cooling sabotage, telegraphed security fight.
l=base('03a-secondary',3,'First Strike · Jessie','hub',1728,'jessie');l.timer={seconds:70,startFlag:null};intro(l,[say('Jessie','The device is in. Cooling is failing. I’ll shut down the secondary controls.'),say('Janey','I’ll get to the module. Meet at the service hall.'),title('FIRST STRIKE • JESSIE\nTwo controls. One way out.',2000)]);terminal(l,470,'coolant-a','Disable cooling control A');terminal(l,1050,'coolant-b','Disable cooling control B');for(const [x,t]of[[280,'sentinel'],[690,'scrapper'],[900,'watcher'],[1220,'sentinel']])enemy(l,x,222,t);enemy(l,1530,222,'bastion',9,{id:'security-chief',name:'Security head • Bastion stand-in',left:1490,right:1570});crate(l,350);platform(l,560,174,5);pickup(l,620,158,'grenade');hazard(l,820);checkpoint(l,1120);pickup(l,1390);objective(l,'cooling','Disable both secondary controls',['coolant-a','coolant-b']);objective(l,'security','Defeat the security head',['dead:security-chief']);exit(l,1650,['coolant-a','coolant-b','dead:security-chief'],seq(l,'handoff',[say('Jessie','Secondary systems are down. Janey, how’s the module?')]));
// 03B — recovery cannot succeed; backtrack to the only unlocked side door.
l=base('03b-module',3,'First Strike · Janey','hub',1440);l.timer={seconds:65,startFlag:null};intro(l,[say('Janey','Module bay ahead. Keep a route back to the hall.'),title('FIRST STRIKE • JANEY\nReach the module bay.',1700)]);for(const [x,t]of[[270,'sentinel'],[540,'collector'],[930,'scrapper']])enemy(l,x,222,t);crate(l,350);platform(l,430,170,5);pickup(l,485,154,'shield');checkpoint(l,740);entity(l,'decor',1240,222,N('module'),'module');enemy(l,1140,222,'bastion',20,{id:'recovery-chief',left:1120,right:1160,activationFlag:'module-left'});entity(l,'solid',1176,156,N('steel-floor'),'bay-barrier',{w:24,h:66});trigger(l,1100,seq(l,'forced-retreat',[say('Janey','Security! The bay is sealed. I can’t reach it.'),flag('module-left'),say('Jessie','Leave the module. Find the service hall — try the side doors!')]),'module-alarm');for(const x of [1000,920])entity(l,'terminal',x,222,N('blast-door'),'locked-'+x,{label:'Test locked door',flag:'tried-'+x,sequence:seq(l,'locked-'+x,[say('Janey','Locked. Keep moving.')])});objective(l,'module','Reach the module bay',['module-left']);objective(l,'retreat','Find the unlocked service door',['module-left']);exit(l,820,['module-left'],seq(l,'reunion',[say('Jessie','Here! Through the yard. Don’t stop for the wrecks.'),flag('reunited')]));l.notes.push('Sequential route presentation. Module is never a collectible; its unrecovered outcome is fixed. Security head uses existing Bastion as a labeled prototype stand-in.');
// 03C — shared escape, readable hazard cadence and optional upper pickups.
l=base('03c-wrecking-yard',3,'First Strike · Wrecking yard','recyke',1392);l.timer={seconds:45,startFlag:null};entity(l,'npc',80,222,null,'jessie',{hero:'jessie',follow:true});intro(l,[say('Jessie','Past the presses, then the alley. Cruiser is at the far end.')]);for(const x of [220,640,980]){hazard(l,x);entity(l,'decor',x+40,222,R('press'));}for(const x of [300,690,1040])enemy(l,x,222,x===690?'manta':'sentinel');crate(l,390);platform(l,440,176,5);pickup(l,490,160,'health');checkpoint(l,800);entity(l,'decor',890,222,R('boiler'));objective(l,'escape','Reach the cruiser before the Hub detonates',[]);exit(l,1300,[],seq(l,'takeoff',[title('The Hub’s cooling system fails.',1800),{type:'flash',duration:1000},say('Jessie','We need to disappear for a few days. Go home to Skyview. Your parents’ place.'),say('Janey','And you?'),say('Jessie','I’ll find somewhere quiet. Go.'),flag('module-left')]),222,'cruiser');
// 04 — party then urgent, peaceful terrace traversal.
l=base('04-skyview',4,'Breaking news in sky view','skyview',1200);entity(l,'npc',130,222,N('father'),'father');entity(l,'npc',220,222,N('guest'),'guest');entity(l,'npc',360,222,N('guest'));entity(l,'decor',150,166,N('broadcast'),'news');entity(l,'decor',260,222,N('sofa'));for(const x of[450,700,1000]){entity(l,'decor',x,222,N('planter'));entity(l,'decor',x,150,N('glass-roof'));}intro(l,[say('Father','You have opportunities here, Janey. And you spend your time with Jessie in Recyke.'),say('Janey','You say that as if where he lives tells you who he is.'),say('Guest','Turn on the news. Now.'),say('Broadcast','Nexus enforcement is deploying drones and robots to Recyke. Anyone remaining is in danger of death. Uninvolved residents must leave immediately.'),title('The abandoned module let Nexus track Jessie.\nRecyke is under attack.',3400),say('Janey','Jessie’s still there. I’m taking the cruiser.')]);crate(l,600);platform(l,680,186,4);objective(l,'depart','Reach Janey’s cruiser',[]);exit(l,1110,[],seq(l,'departure',[say('Janey','Hold on, Jessie. I’m coming.')]),222,'cruiser');
// 05 / 07 — shared side-view flight, different spatial wave arrangements.
function flight(id,ch,name,theme,width,advanced=false){let f=base(id,ch,name,theme,width,'jane','flight');f.flight.speed=advanced?112:100;intro(f,[say('Janey',advanced?'Regional server. If the code can reach their system, I can finish this.':'Recyke approach. Keep the cruiser clear and look for Jessie.'),title('WASD / arrows to steer • Space to fire\nFly THROUGH holograms to boost • Collect gun icons',2600)]);for(let x=600;x<width-300;x+=430){let n=Math.floor(x/430);enemy(f,x,65+(n%3)*65,n%2?'manta':'watcher',advanced?4:3,{left:x-10,right:x+10,id:'wave-'+x});if(advanced&&n%2===0)enemy(f,x+120,220,'collector',3,{id:'escort-'+x});}for(const [i,x]of[480,1250,2100,3050].entries()){entity(f,'boost',x,75+(i%3)*65,N('boost'),'boost-'+i,{w:56,h:40,duration:2});entity(f,'pickup',x+120,75+(i%3)*65,N('weapon'),'weapon-'+i,{pickup:'weapon'});}for(const x of[900,1800,2900])entity(f,'pickup',x,135,N('health'),null,{pickup:'health'});objective(f,'arrive',advanced?'Reach the regional server':'Reach Recyke',[]);f.onComplete=seq(f,'arrival',[say('Janey',advanced?'There. The perimeter fence.':'I see the impact. Jessie, answer me!')]);return f;}
flight('05-reaching-out',5,'Reaching Out','recyke',3900);
// 06 — stealth is a fail/retry system; story death occurs only after success.
l=base('06-untitled',6,'Chapter 6 · Untitled','ruin',1296,'jessie');l.stealth=true;entity(l,'decor',50,222,N('desk'),'workstation');for(const x of[160,250])entity(l,'npc',x,222,N('operative'));for(const x of[210,410,640,850,1050]){entity(l,'cover',x,222,N('cover'),'cover-'+x,{w:48,h:24});entity(l,'decor',x+24,222,N('rubble'),null,{layer:'foreground'});}enemy(l,460,222,'sentinel',3,{id:'search-one',left:425,right:505,facing:1});enemy(l,895,222,'sentinel',3,{id:'search-two',left:865,right:945,facing:1});platform(l,320,171,8);crate(l,285,true);platform(l,760,170,9);crate(l,720,true);checkpoint(l,650);intro(l,[say('Jessie','The network’s going quiet. Anyone else seeing—'),title('MISSILE INBOUND',1400),{type:'flash',duration:1300},say('Jessie','I’m here. Still here.'),title('STAY UNSEEN\nCrouch in dark cover • Use the overhead maintenance walks\nDetection is recoverable. Reach the exposed wall.',3400)]);objective(l,'unseen','Reach the exposed wall without being detected',[]);exit(l,1200,[],seq(l,'rescue',[{type:'spawn-visual',assetId:N('cruiser'),x:1250,y:190,duration:1300},say('Janey','Jessie! Over here!'),say('Jessie','Janey!'),move('player',1230,222,900),{type:'flash',duration:140},{type:'visibility',actor:'player',visible:false,duration:1},title('A shot cuts through the opening.\nJessie falls. Janey cannot reach him.',3600),flag('jessie-dead'),say('Janey','Jessie…'),title('The cruiser disappears into the smoke.',2300)]));l.notes.push('Approved hero art has no death animation. Death uses a cutaway/title and hidden actor, never a fabricated approved pose. Chapter title intentionally unresolved.');
flight('07-ctrl-alt-del',7,'Ctrl Alt Del','server',4500,true);
// 08 — fence climb handoff, rear bat strike, then mixed-room combat.
l=base('08-acquire',8,'Aquire this!','server',1776);entity(l,'ladder',175,222,N('fence'),'perimeter-fence',{w:24,h:64,top:158,flag:'climbed'});entity(l,'solid',175,166,N('steel-floor'),'perimeter-barrier',{w:24,h:56});platform(l,199,158,3);enemy(l,325,222,'sentinel',3,{id:'rear-guard',left:325,right:325,facing:1,passive:true,backstab:true});intro(l,[say('Janey','Fence first. The guard’s looking away.'),title('Hold W / Up at the fence to climb.\nLand behind the guard and press F for a bat strike.',2800)]);trigger(l,365,seq(l,'inside',[say('Janey','The hub is deeper inside. Keep moving.'),flag('entered-server')]),'inside-trigger',['climbed','dead:rear-guard']);for(const[x,t]of[[530,'sentinel'],[760,'collector'],[990,'scrapper'],[1230,'manta'],[1530,'bastion']])enemy(l,x,222,t,t==='bastion'?7:3);crate(l,650);platform(l,800,172,5);pickup(l,850,157,'grenade');checkpoint(l,1110);terminal(l,1390,'server-access','Unlock server hub');hazard(l,1460);pickup(l,1650);objective(l,'breach','Climb the fence and strike the rear guard',['climbed','dead:rear-guard']);objective(l,'hub','Unlock the regional hub',['server-access']);exit(l,1710,['climbed','dead:rear-guard','server-access'],seq(l,'hub-arrival',[say('Janey','There’s the interface. Time to upload the code.')]));l.equipment={bat:true};
// 09 — hack starts timer, finite stolen guns; melee always prevents an ammo softlock.
l=base('09-server-escape',9,'Chapter 9 · Server escape','server',1968);l.equipment={scavengeOnly:true,ammo:12,bat:true};l.timer={seconds:75,startFlag:'uploaded'};terminal(l,120,'uploaded','Upload the code',[],seq(l,'upload',[say('Janey','This is for everyone you left in Recyke.'),title('UPLOAD COMPLETE\nCooling cascade initiated.',1800)]));intro(l,[say('Janey','One upload. Then get out.'),title('Stolen robot guns have finite ammo.\nE beside a fallen robot to take its gun. G discards it.\nF always strikes, even with an empty weapon.',3400)]);for(const[x,t]of[[340,'sentinel'],[560,'scrapper'],[810,'watcher'],[1030,'sentinel'],[1270,'collector'],[1510,'scrapper'],[1730,'bastion']])enemy(l,x,222,t,t==='bastion'?7:3,{dropsGun:true});for(const x of[450,920,1430])hazard(l,x);platform(l,650,170,5);pickup(l,710,154,'shield');checkpoint(l,1130);pickup(l,1630);terminal(l,1330,'escape-lock','Release evacuation shutter',['uploaded']);objective(l,'upload','Upload the code',['uploaded']);objective(l,'escape','Release the shutter and escape',['escape-lock']);exit(l,1890,['uploaded','escape-lock'],seq(l,'detonation',[{type:'flash',duration:1000},title('The regional server goes dark.',2000)]));
// 10 — roof panorama, original vow explicitly provisional.
l=base('10-never-say-die',10,'Never say Die','server',960);l.entities=l.entities.filter(e=>e.layer!=='architecture');l.spawn={x:410,y:222,hero:'jane'};for(const x of[100,800])entity(l,'decor',x,222,N('antenna'));intro(l,[camera(170,0,1),say('Janey','You told me the code would be hard to carry.'),say('Janey','You were right, Jessie.'),camera(170,-80,2600),say('Janey','I’m still here. And I’m not done fighting.'),title('NEVER SAY DIE',3300),title('CTRL ALT DEL — EPISODE I\nStory direction: supplied lead-designer outline\nPrototype campaign, dialogue and environment studies\nOriginal album / final credits pending',6000),flag('episode-complete'),{type:'complete',duration:1}]);
// Interior spaces use a ceiling service run, not an outdoor skyline. Repetition is
// broken by controlled service bays; all placements remain explicit and editable.
for(const room of levels.filter(v=>['hideout','hub','server','ruin'].includes(v.theme)&&v.mode==='ground'&&v.chapter!==10)){
 room.entities=room.entities.filter(e=>e.layer!=='distant');
 for(let x=0;x<room.bounds.width;x+=192){
  entity(room,'decor',x,105,R('pipe-horizontal'),'overhead-'+x,{layer:'architecture'});
  entity(room,'decor',x+100,115,R('vent-fan'),'vent-'+x,{layer:'architecture'});
  if(room.theme==='hub'&&x%384===0)entity(room,'decor',x+120,222,R('boiler'),'cooling-stack-'+x,{layer:'scenery'});
  if(room.theme==='hideout')entity(room,'decor',x+148,212,R('poster'),'wall-notice-'+x,{layer:'architecture',variant:(x/192)%2});
 }
 if(room.theme==='ruin')room.entities=room.entities.filter(e=>!(e.layer==='architecture'&&e.x>1056&&!e.id.startsWith('vent')));
}
for(const flightRoom of levels.filter(v=>v.mode==='flight'&&v.chapter===7))for(let x=320;x<flightRoom.bounds.width;x+=384)entity(flightRoom,'decor',x,244,N('antenna'),'regional-mast-'+x,{layer:'distant'});
const exposedExit=levels.find(v=>v.chapter===6).entities.find(e=>e.id==='exit');delete exposedExit.assetId;delete exposedExit.assetRevision;exposedExit.label='Signal the cruiser';
const opening=levels[0];opening.entities.find(e=>e.id==='jessie').followInScene=true;
opening.sequences.opening.cards=opening.sequences.opening.cards.filter(c=>!(c.type==='move'&&c.actor==='jessie'&&c.x!==1390));
let prevWalkX=opening.spawn.x;for(const c of opening.sequences.opening.cards)if(c.type==='move'&&c.actor==='player'){c.duration=Math.max(500,Math.round(Math.abs(c.x-prevWalkX)/40*1000));prevWalkX=c.x;}
for(let i=0;i<levels.length;i++){let l=levels[i];l.next=levels[i+1]?.id||null;fs.writeFileSync(path.join(root,'levels',l.id+'.json'),JSON.stringify(l,null,2)+'\n');}fs.writeFileSync(path.join(root,'levels/campaign.json'),JSON.stringify({schemaVersion:1,id:'episode-i',title:'Ctrl Alt Del · Episode I',status:'prototype',entry:levels[0].id,levels:levels.map(l=>({id:l.id,chapter:l.chapter,title:l.title,mode:l.mode,file:'levels/'+l.id+'.json'})),storySource:'../docs/story/lead-designer-original.txt',decisions:{family:'mini-only',firstStrike:'sequential Jessie → Janey → shared yard escape',flight:'side-view',dialogue:'prototype writing except exact supplied source lines'},unresolved:['Album audio and cue sheet','Final password','Moral Code emblem','Titles for chapters 6 and 9','Final supporting cast and cruiser art','Exact album dialogue and credits']},null,2)+'\n');console.log(levels.length+' editable levels written.');
