/* Declarative campaign simulation. Authored documents are cloned; runtime state never writes back. */
(function(root,factory){const a=factory(typeof module==='object'?require('./schema.js'):root.EP1Data,typeof module==='object'?require('./ground.js'):root.EP1Ground);if(typeof module==='object')module.exports=a;else root.EP1Mission=a;})(globalThis,function(D,G){
'use strict';const {clone,clamp,overlap}=D;
function create(document,registry,options={}){const l=clone(document),assets=new Map(registry.assets.map(a=>[a.assetId,a])),geom=D.geometry(l,assets);let ground,s,checkpointSave,previous={},queueAfter=null;let uid=0;
const condition=f=>f.startsWith('dead:')?s.world.enemies.some(e=>e.uid===f.slice(5)&&e.dead):!!s.flags[f];const ready=e=>(e.requires||[]).every(condition);const notify=(text)=>{s.notice=text;s.noticeTime=4;};
function initialize(){const enemyDefs=l.entities.filter(e=>e.kind==='enemy').map((e,i)=>({id:e.archetype,uid:e.id,x:e.x,y:e.y,left:e.left??e.x,right:e.right??e.x,hp:e.hp,facing:e.facing||-1,sourceId:e.id,passive:e.passive,backstab:e.backstab,enabled:false}));
 if(l.mode==='ground'){ground=G.create({hero:l.spawn.hero,random:()=>.5,level:{worldWidth:l.bounds.width,height:270,killY:l.bounds.height,safeUntilX:0,spawn:options.start||l.spawn,platforms:geom,enemies:enemyDefs,pickups:[],zones:[{x:0,name:l.title,hint:''}],checkpoint:{x:-9999,y:0},exit:{x:l.bounds.width+1000,y:222},stealth:!!l.stealth}});}
 s={version:1,levelId:l.id,time:0,flags:{},used:[],objects:{},actors:l.entities.filter(e=>e.kind==='npc').map(e=>({...e,visible:true,state:'idle'})),visuals:[],sequence:null,sequenceIndex:0,sequenceTime:0,cardStarted:false,cameraOverride:null,hiddenPlayer:false,paused:false,won:false,dead:false,reason:'',notice:'',noticeTime:0,timer:l.timer?.seconds??null,timerStarted:!l.timer?.startFlag,watch:0,watchCharge:4,grenades:2,shield:0,detection:0,drops:[],score:0,checkpointId:null,world:ground?ground.raw():{player:{x:l.spawn.x,y:l.spawn.y,hp:8,maxHp:8,hero:'jane',facing:1,state:'idle',stateTime:0,invulnerable:1,ammo:null},enemies:enemyDefs.map(e=>({...e,drone:true,dead:false,spawnY:e.y,maxHp:e.hp,state:'patrol',stateTime:0,cooldown:.8})),shots:[],effects:[],camera:0,time:0,dead:false,won:false},route:0,boost:0,flightWeapon:0};
 const p=s.world.player;p.damageMultiplier=1;if(l.equipment?.scavengeOnly)p.ammo=l.equipment.ammo??12;
 previous={};checkpointSave=null;uid=0;if(l.onStart&&!options.skipIntro)startSequence(l.onStart);return s;}
function startSequence(id,after=null){if(!l.sequences[id]){notify('Missing sequence: '+id);return;}s.sequence=id;s.sequenceIndex=0;s.sequenceTime=0;s.cardStarted=false;queueAfter=after;s.cameraOverride=null;}
function actor(id){return id==='player'?s.world.player:s.actors.find(a=>a.id===id);}
function beginCard(c){s.cardStarted=true;s.sequenceTime=0;s.cardStartCamera={x:s.cameraOverride?.x??s.world.camera??0,y:s.cameraOverride?.y??0};const a=actor(c.actor);if(a)s.cardStartActor={x:a.x,y:a.y};
 if(c.type==='flag')s.flags[c.flag]=c.value!==false;
 if(c.type==='object')s.objects[c.target]={state:c.state,time:0};
 if(c.type==='visibility'){if(c.actor==='player')s.hiddenPlayer=!c.visible;else if(a)a.visible=c.visible;}
 if(c.type==='spawn-visual')s.visuals.push({...c,id:'visual-'+(++uid),layer:'actors'});
 if(c.type==='complete'){s.won=true;s.flags['completed:'+l.id]=true;}
}
function finishCard(c){if(c.type==='move'){const a=actor(c.actor);if(a){a.x=c.x;a.y=c.y;a.vx=0;a.vy=0;a.state='idle';}}if(c.type==='move'&&c.actor==='player')for(const a of s.actors.filter(a=>a.followInScene)){a.state='idle';a.stateTime=0;}if(c.type==='object'&&s.objects[c.target])s.objects[c.target].time=Math.max(s.objects[c.target].time||0,c.duration/1000);if(c.type==='camera')s.cameraOverride={x:c.x,y:c.y};s.sequenceIndex++;s.sequenceTime=0;s.cardStarted=false;}
function updateSequence(dt,advance=false){if(!s.sequence)return;let seq=l.sequences[s.sequence],c=seq.cards[s.sequenceIndex];if(!c){s.sequence=null;s.cameraOverride=null;s.world.player.vx=0;s.world.player.vy=0;s.world.player.state='idle';if(queueAfter==='complete'){s.won=true;s.flags['completed:'+l.id]=true;}queueAfter=null;return;}if(!s.cardStarted)beginCard(c);s.sequenceTime+=dt;const f=clamp(s.sequenceTime/(Math.max(1,c.duration)/1000),0,1),ease=f*f*(3-2*f);if(c.type==='move'){let a=actor(c.actor);if(a){a.x=s.cardStartActor.x+(c.x-s.cardStartActor.x)*f;a.y=s.cardStartActor.y+(c.y-s.cardStartActor.y)*f;a.facing=c.x>=s.cardStartActor.x?1:-1;a.state='walk';a.stateTime=(a.stateTime||0)+dt;if(c.actor==='player')for(const b of s.actors.filter(b=>b.followInScene&&b.visible)){b.x=a.x+30;b.y=a.y;b.facing=a.facing;b.state='walk';b.stateTime=a.stateTime;}if(c.actor==='player')s.world.camera=clamp(a.x-172,0,l.bounds.width-480);}}if(c.type==='camera')s.cameraOverride={x:s.cardStartCamera.x+(c.x-s.cardStartCamera.x)*ease,y:s.cardStartCamera.y+(c.y-s.cardStartCamera.y)*ease};if(f>=1||advance)finishCard(c);}
function skipSequence(){let limit=2000;while(s.sequence&&limit-->0){updateSequence(0,true);}if(limit<=0)throw new Error('Sequence exceeded bounded card limit.');}
function fail(reason){s.dead=true;s.reason=reason;s.world.dead=true;}
function damage(amount){if(ground){ground.damagePlayer(amount,-1);s.dead=s.world.dead;if(s.dead)s.reason='Suit disabled. Retry the checkpoint.';}else{let p=s.world.player;if(p.invulnerable>0)return;p.hp=Math.max(0,p.hp-amount);p.invulnerable=1;if(!p.hp)fail('Cruiser disabled. Retry the route.');}}
function hurtEnemy(e,amount){if(ground)ground.damageEnemy(e,amount,e.x,e.y-18);else{e.hp=Math.max(0,e.hp-amount);if(!e.hp){e.dead=true;e.state='death';e.stateTime=0;}}}
function flightStep(dt,input){const w=s.world,p=w.player;w.time+=dt;p.invulnerable=Math.max(0,p.invulnerable-dt);s.boost=Math.max(0,s.boost-dt);const pace=l.flight.speed*(s.boost>0?1.7:1);s.route=Math.min(l.flight.finishX,s.route+pace*dt);w.camera=clamp(s.route,0,l.bounds.width-480);p.x=clamp(p.x+pace*dt+((input.right?1:0)-(input.left?1:0))*l.flight.steerSpeed*dt,w.camera+38,w.camera+430);p.y=clamp(p.y+((input.down?1:0)-(input.up?1:0))*l.flight.steerSpeed*dt,26,241);p.fireCooldown=Math.max(0,(p.fireCooldown||0)-dt);
 if(input.fire&&p.fireCooldown<=0){for(const dy of s.flightWeapon?[0,-70,70]:[0])w.shots.push({uid:++uid,x:p.x+31,y:p.y,vx:470,vy:dy,life:1.3,hostile:false,damage:1});p.fireCooldown=.16;}
 for(const e of w.enemies){if(e.dead){e.stateTime+=dt;continue;}e.enabled=e.x>w.camera-50&&e.x<w.camera+600;if(!e.enabled)continue;e.stateTime+=dt;e.y=e.spawnY+Math.sin(w.time*1.8+e.x)*9;e.facing=-1;e.cooldown-=dt;const ahead=e.x-p.x;if(ahead>0&&ahead<380&&e.cooldown<0){e.cooldown=1.8;e.state='fire';const dx=p.x-e.x,dy=p.y-(e.y-21),len=Math.hypot(dx,dy);w.shots.push({uid:++uid,x:e.x,y:e.y-21,vx:dx/len*130,vy:dy/len*130,life:5,hostile:true,damage:1});}else e.state='patrol';if(Math.abs(p.x-e.x)<29&&Math.abs(p.y-(e.y-21))<17)damage(1);}
 for(const b of w.shots){const oldX=b.x,oldY=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;const seg={x:Math.min(oldX,b.x)-2,y:Math.min(oldY,b.y)-2,w:Math.abs(b.x-oldX)+4,h:Math.abs(b.y-oldY)+4};if(b.hostile){if(overlap(seg,{x:p.x-24,y:p.y-9,w:48,h:18})){damage(1);b.life=0;}}else for(const e of w.enemies)if(e.enabled&&!e.dead&&overlap(seg,{x:e.x-10,y:e.y-30,w:20,h:18})){hurtEnemy(e,1);b.life=0;break;}}
 w.shots=w.shots.filter(b=>b.life>0);if(s.route>=l.flight.finishX){if(l.onComplete)startSequence(l.onComplete,'complete');else s.won=true;}}
function use(e){const p=s.world.player;if(!ready(e)){notify('Still needed: '+(e.requires||[]).filter(f=>!condition(f)).join(', '));return;}if(e.kind==='exit'){if(e.sequence)startSequence(e.sequence,'complete');else{s.won=true;s.flags['completed:'+l.id]=true;}return;}if(e.kind==='terminal'){if(s.used.includes(e.id)){notify('Already activated.');return;}s.used.push(e.id);if(e.flag)s.flags[e.flag]=true;s.objects[e.id]={state:'active',time:0};notify(e.label+' — complete');if(e.sequence)startSequence(e.sequence);}}
function pickupsAndObjects(dt,input){const p=s.world.player;let nearest=null,dist=Infinity;s.prompt=null;
 for(const e of l.entities){const near=Math.abs(p.x-e.x)<25&&Math.abs(p.y-(l.mode==='flight'?e.y:e.y))<45;
 if(['terminal','exit'].includes(e.kind)&&near&&Math.abs(p.x-e.x)<dist){nearest=e;dist=Math.abs(p.x-e.x);}
 if(e.kind==='checkpoint'&&near&&!s.used.includes(e.id)){s.used.push(e.id);p.hp=p.maxHp;s.shield=Math.max(s.shield,1);s.checkpointId=e.id;notify('Checkpoint saved • health restored');checkpointSave=serialize();}
 if(e.kind==='pickup'&&!s.used.includes(e.id)&&Math.abs(p.x-e.x)<(l.mode==='flight'?32:14)&&Math.abs((l.mode==='flight'?p.y:p.y-13)-e.y)<23){if(e.pickup==='health'&&p.hp>=p.maxHp)continue;s.used.push(e.id);if(e.pickup==='health'){p.hp=Math.min(p.maxHp,p.hp+3);notify('Repair kit • +3 health');}if(e.pickup==='shield'){s.shield=6;notify('Shield battery • 6 seconds');}if(e.pickup==='grenade'){s.grenades+=2;notify('Two pulse grenades • Q');}if(e.pickup==='weapon'){s.flightWeapon=1;notify('Spread cannon acquired');}}
 if(e.kind==='boost'&&!s.used.includes(e.id)&&Math.abs(p.x-e.x)<e.w/2+28&&Math.abs(p.y-e.y)<e.h/2+9){s.used.push(e.id);s.boost=e.duration||2;notify('Propaganda scrambled • BOOST');}
 if(e.kind==='trigger'&&ready(e)&&(!e.once||!s.used.includes(e.id))&&overlap({x:p.x-5,y:p.y-30,w:10,h:30},{x:e.x,y:e.y,w:e.w,h:e.h})){s.used.push(e.id);if(e.flag)s.flags[e.flag]=true;if(e.sequence)startSequence(e.sequence);}
 if(e.kind==='hazard'&&s.time%(e.period||3)<(e.onDuration||1)&&overlap({x:p.x-5,y:p.y-(p.crouching?16:30),w:10,h:p.crouching?16:30},{x:e.x,y:e.y-e.h,w:e.w,h:e.h}))damage(e.damage||1);
 }
 if(nearest){s.prompt='E • '+(nearest.label||nearest.name)+(ready(nearest)?'':' (locked)');if(input.interact&&!previous.interact)use(nearest);}
 for(const drop of s.drops){if(!drop.taken&&Math.abs(drop.x-p.x)<28&&Math.abs(drop.y-p.y)<30){s.prompt='E • Take robot gun (12 rounds)';if(input.interact&&!previous.interact){drop.taken=true;p.ammo=12;s.weaponsTaken=(s.weaponsTaken||0)+1;notify('Robot gun • 12 rounds');}}}
}
function mechanics(dt,input){const w=s.world,p=w.player;s.shield=Math.max(0,s.shield-dt);if(s.shield>0)p.invulnerable=Math.max(.1,p.invulnerable||0);s.watch=Math.max(0,s.watch-dt);p.damageMultiplier=s.watch>0&&p.hero==='jane'?2:1;
 if(input.watch&&!previous.watch&&s.watchCharge>=4&&l.mode==='ground'&&!l.stealth){s.watch=30;s.watchCharge=0;notify(p.hero==='jane'?'Hologram • double damage for 30 seconds':'Watch pulse • nearby enemies stunned for 30 seconds');}
 if(input.grenade&&!previous.grenade&&s.grenades>0&&ground&&!l.stealth){s.grenades--;for(const e of w.enemies)if(!e.dead&&e.enabled!==false&&Math.abs(e.x-(p.x+p.facing*65))<90&&Math.abs(e.y-p.y)<70&&ground.clearRay(p.x,p.y-20,e.x,e.y-20))hurtEnemy(e,4);w.effects.push({x:p.x+p.facing*65,y:p.y-18,kind:'pulse',life:.4,maxLife:.4});notify('Pulse grenade');}
 if(input.discard&&!previous.discard&&l.equipment?.scavengeOnly){p.ammo=0;notify('Weapon discarded • F to strike; E to scavenge');}
 for(const e of w.enemies){const def=l.entities.find(v=>v.id===e.uid);e.enabled=(!def?.activationFlag||condition(def.activationFlag))&&p.x>=(def?.activationX||0);if(def?.passive)e.stunned=dt+.1;if(s.watch>0&&p.hero==='jessie'&&Math.abs(e.x-p.x)<150)e.stunned=dt+.1;
 if(e.dead&&!s.used.includes('reward:'+e.uid)){s.used.push('reward:'+e.uid);s.watchCharge=Math.min(4,s.watchCharge+1);s.score+=100;if(def?.dropsGun||l.equipment?.scavengeOnly)s.drops.push({id:'drop:'+e.uid,x:e.x,y:e.y,taken:false});}
 }
 if(l.stealth){let hiding=l.entities.some(e=>e.kind==='cover'&&p.crouching&&p.x>e.x-5&&p.x<e.x+e.w+5);let seen=w.enemies.some(e=>!e.dead&&e.enabled&&Math.abs(e.x-p.x)<135&&(p.x-e.x)*e.facing>0&&Math.abs(e.y-p.y)<27&&!hiding&&ground.clearRay(e.x,e.y-22,p.x,p.y-(p.crouching?10:22)));s.detection=clamp(s.detection+(seen?dt*.85:-dt*1.4),0,1);if(s.detection>=1)fail('Detected by a search patrol. Use cover or the upper maintenance walks.');}
 for(const a of s.actors)if(a.follow){const dx=p.x-35-a.x;a.x+=clamp(dx,-90*dt,90*dt);a.facing=dx>=0?1:-1;a.state=Math.abs(dx)>5?'run':'idle';a.stateTime=(a.stateTime||0)+dt;}
}
function step(dt,input={}){dt=clamp(Number(dt)||0,0,.05);if(s.paused||s.won||s.dead){previous={...input};return s;}if(s.sequence){updateSequence(dt,!!input.advance&&!previous.advance);s.time+=dt;for(const v of Object.values(s.objects))v.time=(v.time||0)+dt;previous={...input};return s;}s.time+=dt;s.noticeTime=Math.max(0,s.noticeTime-dt);
 mechanics(dt,input);
 if(ground){const p=s.world.player,ladder=l.entities.find(e=>e.kind==='ladder'&&Math.abs(p.x-(e.x+e.w/2))<26&&p.y>e.top-2);if(ladder&&input.up){p.x=ladder.x+ladder.w/2;p.y=Math.max(ladder.top,p.y-65*dt);p.vy=0;p.vx=0;p.state='walk';p.stateTime+=dt;p.invulnerable=.1;s.prompt='W / Up • climb';if(p.y<=ladder.top){p.x=ladder.x+ladder.w+8;p.onGround=true;s.flags[ladder.flag||'climbed']=true;}}else{const controls={...input,swap:false};if(l.stealth){controls.fire=false;controls.melee=false;}ground.update(dt,controls);}s.world=ground.raw();s.world.cameraY=(s.world.cameraY||0)+(clamp(s.world.player.y-205,0,l.bounds.height-270)-(s.world.cameraY||0))*Math.min(1,dt*8);if(s.world.dead){s.dead=true;s.reason='Suit disabled. Retry the checkpoint.';}}
 else flightStep(dt,input);
 if(!s.dead&&!s.sequence)pickupsAndObjects(dt,input);
 if(l.timer&&(!l.timer.startFlag||condition(l.timer.startFlag)))s.timerStarted=true;
 // Interaction/escape resolves before expiry; cutscenes and pause stop mission timers.
 if(s.timerStarted&&s.timer!==null&&!s.sequence&&!s.won&&!s.dead){s.timer=Math.max(0,s.timer-dt);if(s.timer===0)fail('Time expired. Retry from your checkpoint.');}
 for(const v of Object.values(s.objects))v.time=(v.time||0)+dt;
 previous={...input};return s;}
function serialize(){return clone({version:1,levelId:l.id,state:s,queueAfter});}
function restore(saved){if(saved.version!==1||saved.levelId!==l.id)throw Error('Checkpoint belongs to a different level/version.');s=clone(saved.state);s.paused=false;s.dead=false;s.reason='';s.world.dead=false;if(ground){ground.restore(s.world);s.world=ground.raw();}queueAfter=saved.queueAfter;previous={};return s;}
function retry(){if(checkpointSave){let save=clone(checkpointSave);restore(save);s.world.player.invulnerable=1;notify('Checkpoint restored');return s;}return initialize();}
initialize();return{level:l,step,state:()=>s,condition,ready,startSequence,skipSequence,retry,restart:initialize,pause(v){s.paused=!!v;previous={};},serialize,restore,geometry:geom,objectives:()=>l.objectives.map(o=>({...o,done:(o.requires||[]).length>0&&(o.requires||[]).every(condition)}))};
}
return{create};});
