/* Shared native renderer for play, editor, previews and exported documents. */
window.EP1Render=(()=>{
const D=EP1Data;let registry,assets,images=new Map(),metas=new Map(),actors;
async function load(){registry=await(await fetch('assets/registry.json')).json();assets=new Map(registry.assets.map(a=>[a.assetId,a]));actors=new Map(registry.characters.map(a=>[a.id,a]));const urls=new Set([...registry.assets.flatMap(a=>a.render.variants.map(v=>v.uri)),...registry.characters.map(a=>a.uri)]);await Promise.all([...urls].map(uri=>new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>{images.set(uri,im);resolve();};im.onerror=()=>reject(Error('Cannot load '+uri));im.src=uri;})));await Promise.all(registry.characters.map(async a=>metas.set(a.id,await(await fetch(a.metadata)).json())));return registry;}
function frame(a,state,time){const st=a.animation.states[state]||a.animation.states.idle||Object.values(a.animation.states)[0];if(!st)return 0;const sum=st.timingMs.reduce((n,v)=>n+v,0);let t=st.loop?time*1000%sum:Math.min(time*1000,sum-.01),i=0;while(t>=st.timingMs[i]&&i<st.frames.length-1)t-=st.timingMs[i++];return st.frames[i];}
function asset(c,id,x,y,opts={}){const a=assets.get(id);if(!a){c.fillStyle='#653a86';c.fillRect(Math.round(x)-8,Math.round(y)-16,16,16);c.fillStyle='#f9d991';c.fillRect(Math.round(x)-1,Math.round(y)-13,2,7);return;}const v=a.render.variants[opts.variant||0]||a.render.variants[0],im=images.get(v.uri),w=a.native.width,h=a.native.height;let f=opts.frame??frame(a,opts.state||'idle',opts.time||0);c.drawImage(im,f*w,0,w,h,Math.round(x)-a.native.origin[0],Math.round(y)-a.native.origin[1],w,h);}
function actor(c,id,p,time=0){const ref=actors.get(id),m=metas.get(id);if(!ref||!m)return;let state=m.rows.includes(p.state)?p.state:'idle',row=m.rows.indexOf(state),holds=m.timingMs[state],sum=holds.reduce((n,v)=>n+v,0),t=m.loops?.[state]===false?Math.min(time*1000,sum-.001):(time*1000)%sum,i=0;while(t>=holds[i]&&i<holds.length-1)t-=holds[i++];c.save();c.translate(Math.round(p.x),Math.round(p.y));if(p.facing===-1)c.scale(-1,1);c.drawImage(images.get(ref.uri),i*48,row*48,48,48,-20,-40,48,48);c.restore();}
function tiled(c,e){const a=assets.get(e.assetId);if(!a)return;let w=e.w,h=e.h;c.save();c.beginPath();c.rect(e.x,e.y,w,h);c.clip();for(let y=e.y;y<e.y+h;y+=a.native.height)for(let x=e.x;x<e.x+w;x+=a.native.width)asset(c,e.assetId,x+a.native.origin[0],y+a.native.origin[1],{variant:e.variant});c.restore();}
function draw(c,l,s=null,opts={}){const W=c.canvas.width,H=c.canvas.height,time=s?.time||opts.time||0,world=s?.world,cam=opts.camera||s?.cameraOverride||{x:world?.camera||0,y:world?.cameraY||0};const cx=Math.round(cam.x),cy=Math.round(cam.y);c.imageSmoothingEnabled=false;c.fillStyle=l.theme==='skyview'?'#29364d':l.theme==='server'?'#101620':'#101221';c.fillRect(0,0,W,H);c.fillStyle=l.theme==='skyview'?'#42536a':'#1d2634';c.fillRect(0,Math.round(80-cy),W,H);c.fillStyle='#29364d';c.fillRect(0,Math.round(140-cy),W,18);
 c.save();c.translate(-cx,-cy);const terrainMap=new Set((l.terrain||[]).map(t=>t.x+','+t.y));
 const hidden=opts.hidden||new Set();const order=[...l.layers].sort((a,b)=>a.order-b.order).map(a=>a.id);for(const layer of order){if(hidden.has(layer))continue;
 for(const e of l.entities){if(e.layer!==layer||e.kind==='enemy'||e.hero||e.hidden)continue;const b=D.box(e,assets);if(b.x+b.w<cx||b.x>cx+W||b.y+b.h<cy||b.y>cy+H)continue;if(s?.used.includes(e.id)&&e.kind==='pickup')continue;if(['trigger'].includes(e.kind)){continue;}let anim=s?.objects[e.id],frameOverride;if(e.kind==='terminal'&&s?.used.includes(e.id))frameOverride=e.assetId?.endsWith('blast-door')?0:1;if(e.kind==='exit'&&e.assetId?.endsWith('blast-door'))frameOverride=opts.mission?.ready(e)?2:0;if(e.kind==='checkpoint'&&s?.used.includes(e.id))frameOverride=1;
 if(e.kind==='solid'||e.kind==='platform'){tiled(c,e);}else if(e.kind==='hazard'){if(time%(e.period||3)<(e.onDuration||1.35))asset(c,e.assetId,e.x,e.y,{time});else{c.fillStyle='#29364d';c.fillRect(e.x,e.y-3,e.w,3);c.fillStyle='#efb35d';c.fillRect(e.x,e.y-3,4,2);}}else if(e.kind==='npc'&&s){const a=s.actors.find(a=>a.id===e.id);if(a?.visible!==false)asset(c,e.assetId,a?.x??e.x,a?.y??e.y,{time});}else asset(c,e.assetId,e.x,e.y,{variant:e.variant,state:anim?.state||e.state||'idle',time:anim?.time??(time+(e.animationOffset||0)),frame:frameOverride});
 if(['terminal','checkpoint','exit','ladder'].includes(e.kind)&&opts.markers!==false){c.fillStyle=e.kind==='checkpoint'?'#8fcac0':e.kind==='exit'?'#b7df53':'#efb35d';c.fillRect(Math.round(e.x)-2,Math.round(e.y)-52,4,2);}
 }
 if(layer==='playable')for(const t of l.terrain||[]){const mask=(terrainMap.has(t.x+','+(t.y-24))?1:0)+(terrainMap.has((t.x+24)+','+t.y)?2:0)+(terrainMap.has(t.x+','+(t.y+24))?4:0)+(terrainMap.has((t.x-24)+','+t.y)?8:0);const id=t.material==='recyke'?'cad.mini.recyke.street-'+mask.toString(16):t.material==='stone'?'cad.mini.episode1.stone-floor':'cad.mini.episode1.steel-floor';asset(c,id,t.x,t.y,{variant:t.material==='recyke'?(t.variant||0):0});}
 if(layer==='actors'){
 if(s){for(const a of s.actors)if(a.hero&&a.visible!==false)actor(c,a.hero,a,a.stateTime||time);for(const e of world.enemies){if(e.enabled===false&&!opts.editor)continue;if(e.dead&&e.stateTime>1)continue;actor(c,e.id,e,e.stateTime||time);if(!e.dead){c.fillStyle='#101620';c.fillRect(Math.round(e.x)-10,Math.round(e.y)-44,20,2);c.fillStyle=e.mode==='charge'?'#efb35d':'#a6504d';c.fillRect(Math.round(e.x)-10,Math.round(e.y)-44,Math.ceil(e.hp/(e.maxHp||e.hp)*20),2);}}
 const p=world.player;if(!s.hiddenPlayer){if(l.mode==='flight')asset(c,'cad.mini.episode1.cruiser',p.x,p.y,{time});else{if(s.shield>0||s.watch>0){c.strokeStyle=s.shield>0?'#8fcac0':'#b7df53';c.setLineDash([2,3]);c.strokeRect(Math.round(p.x)-17,Math.round(p.y)-38,34,40);c.setLineDash([]);}if(s.watch>0&&p.hero==='jane'){c.save();c.globalAlpha=.45;actor(c,p.hero,{...p,x:p.x-30},p.stateTime);c.restore();}if(!(p.invulnerable>.1&&Math.floor(time*12)%2))actor(c,p.hero,p,p.stateTime||0);if(l.equipment?.bat&&p.attackTime>0)asset(c,'cad.mini.episode1.bat',p.x+p.facing*17,p.y-20);}}
 for(const b of world.shots){c.fillStyle=b.hostile?'#efb35d':'#b7df53';c.fillRect(Math.round(b.x)-2,Math.round(b.y)-1,5,2);}
 for(const d of s.drops)if(!d.taken)asset(c,'cad.mini.episode1.gun',d.x,d.y-6,{time});
 for(const v of s.visuals)asset(c,v.assetId,v.x,v.y,{time});
 for(const e of world.effects){c.strokeStyle=e.kind==='pulse'?'#8fcac0':'#efb35d';const radius=e.kind==='pulse'?Math.round((1-e.life/e.maxLife)*60):4;c.strokeRect(Math.round(e.x)-radius,Math.round(e.y)-radius,radius*2,radius*2);}
 }else{for(const e of l.entities)if(e.kind==='enemy')actor(c,e.archetype,{...e,state:'idle'},time);else if(e.hero)actor(c,e.hero,{...e,state:'idle'},time);if(l.mode==='ground')actor(c,l.spawn.hero,{...l.spawn,state:'idle'},0);else asset(c,'cad.mini.episode1.cruiser',l.spawn.x,l.spawn.y,{time});}
 }
 }
 if(l.stealth&&s){for(const e of world.enemies){if(e.dead)continue;c.save();c.globalAlpha=.12;c.fillStyle='#efb35d';c.beginPath();c.moveTo(e.x,e.y-22);c.lineTo(e.x+e.facing*135,e.y-45);c.lineTo(e.x+e.facing*135,e.y-1);c.closePath();c.fill();c.restore();}for(const e of l.entities.filter(e=>e.kind==='cover')){c.fillStyle='#8fcac0';c.fillRect(e.x+4,e.y-3,e.w-8,1);}}
 if(opts.geometry){for(const b of D.geometry(l,assets)){c.strokeStyle=b.oneWay?'#8fcac0':'#b7df53';c.setLineDash(b.oneWay?[3,2]:[]);c.strokeRect(b.x+.5,b.y+.5,b.w-1,b.h-1);}c.setLineDash([]);for(const e of l.entities.filter(e=>['trigger','hazard','cover','ladder','boost','exit'].includes(e.kind))){const b=D.box(e,assets);c.strokeStyle=e.kind==='hazard'?'#f09077':'#efb35d';c.strokeRect(b.x+.5,b.y+.5,b.w-1,b.h-1);}if(world&&l.mode==='ground'){let p=world.player;c.strokeStyle='#f0a4b8';c.strokeRect(Math.round(p.x)-4.5,Math.round(p.y)-(p.crouching?16:30)+.5,9,(p.crouching?16:30)-1);}}
 if(opts.grid){c.strokeStyle='#72838e';c.globalAlpha=.2;c.beginPath();for(let x=Math.floor(cx/opts.grid)*opts.grid;x<cx+W;x+=opts.grid){c.moveTo(x+.5,cy);c.lineTo(x+.5,cy+H);}for(let y=Math.floor((cy-(opts.gridOriginY||0))/opts.grid)*opts.grid+(opts.gridOriginY||0);y<cy+H;y+=opts.grid){c.moveTo(cx,y+.5);c.lineTo(cx+W,y+.5);}c.stroke();c.globalAlpha=1;}
 if(opts.editor){c.strokeStyle='#72838e';c.setLineDash([4,4]);c.strokeRect(.5,.5,l.bounds.width-1,l.bounds.height-1);c.setLineDash([]);c.strokeStyle='#b7df53';c.strokeRect(l.spawn.x-5.5,l.spawn.y-30.5,11,31);c.fillStyle='#b7df53';c.fillRect(l.spawn.x-2,l.spawn.y-37,4,4);for(const e of l.entities.filter(e=>e.kind==='enemy'&&opts.selection?.has(e.id))){c.strokeStyle='#efb35d';c.beginPath();c.moveTo(e.left,e.y-36);c.lineTo(e.right,e.y-36);c.stroke();for(const x of[e.left,e.right])c.fillRect(x-1,e.y-39,3,7);}for(const id of opts.selection||[]){const e=l.entities.find(v=>v.id===id);if(!e)continue;const b=D.box(e,assets);c.strokeStyle='#f9d991';c.strokeRect(b.x-.5,b.y-.5,b.w+1,b.h+1);}}
 c.restore();if(s?.sequence){const card=l.sequences[s.sequence]?.cards[s.sequenceIndex];if(card?.type==='flash'){c.fillStyle=Math.floor(s.sequenceTime*15)%2?'#d4ccad':'#101620';c.fillRect(0,0,W,H);}c.fillStyle='#101620';c.fillRect(0,0,W,12);c.fillRect(0,H-12,W,12);}
}
function thumbnail(canvas,id){let c=canvas.getContext('2d'),a=assets.get(id);if(!a)return;canvas.width=a.native.width;canvas.height=a.native.height;c.clearRect(0,0,canvas.width,canvas.height);asset(c,id,a.native.origin[0],a.native.origin[1],{frame:0});}
return{load,draw,asset,actor,thumbnail,get registry(){return registry;},get assets(){return assets;},get images(){return images;}};
})();
