(function(root,factory){const a=factory();if(typeof module==='object')module.exports=a;else root.EP1Data=a;})(globalThis,function(){
'use strict';const clone=v=>JSON.parse(JSON.stringify(v));const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const kinds=['decor','asset','solid','platform','enemy','npc','pickup','terminal','exit','checkpoint','hazard','trigger','cover','ladder','boost'];
const cardTypes=['dialogue','move','camera','title','flag','object','visibility','spawn-visual','flash','complete'];
function box(e,assets){const a=assets?.get(e.assetId);if(['solid','platform','trigger','cover','ladder'].includes(e.kind)&&e.w)return{x:e.x,y:e.kind==='cover'||e.kind==='ladder'?e.y-e.h:e.y,w:e.w,h:e.h};if(e.kind==='enemy')return{x:e.x-20,y:e.y-40,w:48,h:48};if(e.hero)return{x:e.x-20,y:e.y-40,w:48,h:48};if(a)return{x:e.x-a.native.origin[0],y:e.y-a.native.origin[1],w:a.native.width,h:a.native.height};return{x:e.x-8,y:e.y-16,w:16,h:16};}
function geometry(l,assets){let out=[];for(const e of l.entities){if(e.kind==='solid'||e.kind==='platform')out.push({x:e.x,y:e.y,w:e.w,h:e.h,oneWay:e.kind==='platform',entityId:e.id});else if(e.kind==='asset'){const a=assets.get(e.assetId);for(const b of a?.collision.defaults||[])if(b.kind!=='sensor')out.push({x:e.x+b.x,y:e.y+b.y,w:b.width,h:b.height,oneWay:b.kind==='oneWay',entityId:e.id});}}
 for(const t of l.terrain||[])out.push({x:t.x,y:t.y,w:24,h:24,oneWay:false,entityId:'terrain:'+t.x+':'+t.y});return out;}
const overlap=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
function shapeValid(l){return !!l&&typeof l==='object'&&Array.isArray(l.entities)&&Array.isArray(l.terrain)&&Array.isArray(l.layers)&&l.layers.every(v=>v&&typeof v.id==='string'&&Number.isFinite(v.order))&&Array.isArray(l.objectives)&&l.objectives.every(v=>v&&Array.isArray(v.requires)&&v.requires.every(f=>typeof f==='string'))&&l.sequences&&typeof l.sequences==='object'&&!Array.isArray(l.sequences)&&Object.values(l.sequences).every(v=>v&&Array.isArray(v.cards)&&v.cards.every(c=>c&&typeof c==='object'))&&l.entities.every(e=>e&&typeof e==='object'&&Number.isFinite(e.x)&&Number.isFinite(e.y)&&(!e.requires||Array.isArray(e.requires)&&e.requires.every(f=>typeof f==='string'))&&(!e.activationFlag||typeof e.activationFlag==='string'))&&l.terrain.every(t=>t&&Number.isFinite(t.x)&&Number.isFinite(t.y))&&l.bounds&&Number.isFinite(l.bounds.width)&&Number.isFinite(l.bounds.height)&&l.spawn&&Number.isFinite(l.spawn.x)&&Number.isFinite(l.spawn.y);}
function validate(l,registry,allIds){if(!shapeValid(l))return[{severity:'error',code:'structure',path:'document',message:'Invalid level structure. Keep arrays for entities, layers, terrain, objectives and sequence cards; use numeric positions and string condition IDs. Original draft is retained.'}];const messages=[],add=(severity,path,message)=>messages.push({severity,path,message});if(!l||typeof l!=='object')return[{severity:'error',path:'document',message:'Open a level document or campaign bundle.'}];if(l.schemaVersion!==1)add('error','schemaVersion','Unsupported data version. This file stays unchanged; open with a compatible editor.');if(l.family!=='mini')add('error','family','Episode I requires native Mini assets. Resizing is not supported.');if(!['ground','flight'].includes(l.mode))add('error','mode','Choose ground or flight mode.');if(!l.id||typeof l.id!=='string')add('error','id','Give this level a stable identifier.');if(!l.bounds||!Number.isInteger(l.bounds.width)||l.bounds.width<480||!Number.isInteger(l.bounds.height)||l.bounds.height<270)add('error','bounds','Bounds must be integer native pixels, at least 480 × 270.');if(!Array.isArray(l.entities)||!Array.isArray(l.terrain)||!l.sequences||typeof l.sequences!=='object')return[...messages,{severity:'error',path:'document',message:'Level needs entities, terrain and sequence collections.'}];
 const assets=new Map((registry?.assets||[]).map(a=>[a.assetId,a])),ids=new Set(),seqIds=new Set(Object.keys(l.sequences)),flagIds=new Set();
 for(const e of l.entities){if(!e||typeof e!=='object'){add('error','entities','Each entity must be an object.');continue;}if(ids.has(e.id))add('error',e.id,'Duplicate object ID. Duplicate through the editor to assign a new ID.');ids.add(e.id);if(!e.id)add('error','entities','Object is missing its stable ID.');if(!kinds.includes(e.kind))add('error',e.id,'Unknown object behavior: '+e.kind);if(!Number.isInteger(e.x)||!Number.isInteger(e.y))add('error',e.id,'Placement must use whole native pixels.');if(e.assetId&&!assets.has(e.assetId))add('error',e.id,'Missing asset '+e.assetId+'. Relink it; the original reference is retained.');if(e.assetId&&assets.get(e.assetId)?.family!=='mini')add('error',e.id,'Asset family is incompatible with Mini.');if(e.assetRevision&&assets.get(e.assetId)&&assets.get(e.assetId).revision!==e.assetRevision)add('error',e.id,'Asset revision is unavailable. Relink explicitly.');if(e.sequence&&!seqIds.has(e.sequence))add('error',e.id,'Sequence '+e.sequence+' does not exist.');if(['solid','platform','trigger','cover','ladder','hazard','boost'].includes(e.kind)&&(!(e.w>0)||!(e.h>0)))add('error',e.id,'Give gameplay geometry a positive width and height.');if(e.kind==='enemy'){if(!['sentinel','bastion','scrapper','watcher','manta','collector'].includes(e.archetype))add('error',e.id,'Choose a registered enemy archetype.');if(!(e.hp>0)||e.left>e.right)add('error',e.id,'Enemy health and patrol endpoints are invalid.');}if(e.kind==='boost'&&l.mode!=='flight')add('error',e.id,'Boost holograms require flight mode.');if(e.flag)flagIds.add(e.flag);if(e.kind==='enemy')flagIds.add('dead:'+e.id);}
 for(const[sid,s]of Object.entries(l.sequences)){if(!Array.isArray(s.cards)){add('error',sid,'Sequence needs ordered cards.');continue;}for(const [i,c]of s.cards.entries()){if(!cardTypes.includes(c.type))add('error',sid+'.'+i,'Unsupported sequence card: '+c.type);if(!Number.isFinite(c.duration)||c.duration<0||c.duration>120000)add('error',sid+'.'+i,'Card duration must be 0–120000 milliseconds.');if(c.type==='flag')flagIds.add(c.flag);if(c.type==='object'&&!ids.has(c.target))add('error',sid+'.'+i,'Object target does not exist: '+c.target);if(['move','visibility'].includes(c.type)&&c.actor!=='player'&&!ids.has(c.actor))add('error',sid+'.'+i,'Actor target does not exist: '+c.actor);if(c.source==='missing-source')add('warning',sid+'.'+i,'Missing original source text: '+c.text);}}
 for(const e of l.entities)for(const f of[e.activationFlag,...(e.requires||[])].filter(Boolean))if(!flagIds.has(f))add('error',e.id,'Condition '+f+' has no producer in this level.');for(const o of l.objectives||[])for(const f of o.requires||[])if(!flagIds.has(f))add('error',o.id,'Objective condition '+f+' has no producer.');for(const k of['onStart','onComplete'])if(l[k]&&!seqIds.has(l[k]))add('error',k,'Sequence '+l[k]+' does not exist.');if(l.next&&allIds&&!allIds.has(l.next))add('error','next','Destination '+l.next+' is missing from this campaign.');if(l.timer&&(!(l.timer.seconds>0)||l.timer.seconds>3600))add('error','timer','Timer must be between 1 and 3600 seconds.');
 if(!l.spawn||!Number.isInteger(l.spawn.x)||!Number.isInteger(l.spawn.y)||!['jane','jessie'].includes(l.spawn.hero))add('error','spawn','Choose Jane or Jessie and an integer start position.');else if(l.mode==='ground'){let b={x:l.spawn.x-5,y:l.spawn.y-30,w:10,h:30},g=geometry(l,assets);if(g.some(p=>!p.oneWay&&overlap(b,p)))add('error','spawn','Player start overlaps solid geometry. Move the start or obstruction.');if(!g.some(p=>l.spawn.x+5>p.x&&l.spawn.x-5<p.x+p.w&&Math.abs(l.spawn.y-p.y)<1))add('warning','spawn','Start is not on a surface; playtest the landing.');}
 if(!l.entities.some(e=>e.kind==='exit')&&!Object.values(l.sequences).some(s=>s.cards?.some(c=>c.type==='complete'))&&l.mode!=='flight')add('error','exit','This map has no exit or completion sequence.');
 for(const t of l.terrain){if(!Number.isInteger(t.x)||!Number.isInteger(t.y))add('error','terrain','Terrain coordinates must be native integers.');}
 if(l.mode==='flight'&&(!l.flight||!(l.flight.speed>0)||!(l.flight.finishX>l.spawn.x)||l.flight.finishX>l.bounds.width))add('error','flight','Flight needs positive route speed and a finish marker inside its bounds.');
 return messages;}
function remapCopies(items,dx=24,dy=0){const token=Math.random().toString(36).slice(2,8),remap=new Map(items.map(e=>[e.id,e.id+'-copy-'+token])),flags=new Map(items.filter(e=>e.flag).map(e=>[e.flag,e.flag+'-copy-'+token]));const ref=f=>flags.get(f)||(f?.startsWith('dead:')&&remap.has(f.slice(5))?'dead:'+remap.get(f.slice(5)):f);return items.map(e=>{let n=clone(e);n.id=remap.get(e.id);n.x+=dx;n.y+=dy;if(Number.isFinite(n.left))n.left+=dx;if(Number.isFinite(n.right))n.right+=dx;if(n.flag)n.flag=ref(n.flag);if(n.activationFlag)n.activationFlag=ref(n.activationFlag);if(n.requires)n.requires=n.requires.map(ref);if(n.group)n.group+='-copy-'+token;return n;});}
return {shapeValid,clone,clamp,kinds,cardTypes,box,geometry,overlap,validate,remapCopies};});
